### ISSUE TITLE
Debug feature: Performance Monitor Issue

### ISSUE THREAD

**Issue by UnrealKaraulov** [alliedmodders/amxmodx#1025]
https://github.com/alliedmodders/amxmodx/commit/8ee3da24cb811ca5c425bc4aec954eee22ca371d

If someone get problems with using this feature or have any suggestions, please use this issue for it.

**Comment by UnrealKaraulov** [comment]
Closed

**Comment by UnrealKaraulov** [comment]
@dvander I see on older linux os next message: 

`L 12/06/2021 - 08:33:46: [META] ERROR: dll: Failed query plugin '<amxmodx_mm_i386.so>'; Couldn't open file '/home/server/game/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so': /home/server/game/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so: undefined symbol: _ZNSt6chrono3_V212steady_clock3nowEv`

Possible need add something to buildbot ?

**Comment by dvander** [comment]
It's missing linkage to libstdc++.

We find the static library here: https://cs.alliedmods.net/amxmodx/source/AMBuildScript#316
And currently only amxxpc uses it here: https://cs.alliedmods.net/amxmodx/source/compiler/amxxpc/AMBuilder#14

amxmodx_i486.so needs a similar link step, I think.

**Comment by UnrealKaraulov** [comment]
@dvander I do build manual from https://wiki.alliedmods.net/Building_AMX_Mod_X

But get next errors: 
![VirtualBox_UBUNTU LATEST_06_12_2021_10_05_50](https://user-images.githubusercontent.com/88730285/144802411-11f58078-f9fb-4250-9891-380bc88c1de6.png)

**Comment by UnrealKaraulov** [comment]
All **is** need rename to **==** ?

**Comment by dvander** [comment]
Yeah, newer versions of Python will complain about this. It's a bug in the script, we should have used "==" for string comparison.

**Comment by UnrealKaraulov** [comment]
@dvander i tried to add std support in https://github.com/alliedmodders/amxmodx/pull/1026

**Comment by dvander** [comment]
I merged the build fix. I think it should work. You can test by using "ldd -d -r <.so file>" on the command-line, and it should tell you if any symbols are missing.

**Comment by UnrealKaraulov** [comment]
> I merged the build fix. I think it should work. You can test by using "ldd -d -r <.so file>" on the command-line, and it should tell you if any symbols are missing.

It can be added to GitHub actions?

**Comment by rtxa** [comment]
Hi @UnrealKaraulov. Would you mind to explain how this new feature works? I'm using one of the latest commits and I couldn't fail to notice that some of the plugins that I have in debug mode are throwing messages like `[agmodx.amxx] performance issue. Function plugin_init executed more than 100.6ms.`. Can this be disabled without disabling the debug feature in plugins which is useful for other kind of errors?

**Comment by UnrealKaraulov** [comment]
@rtxa now it impossible, see https://github.com/alliedmodders/amxmodx/pull/1027 and https://github.com/alliedmodders/amxmodx/pull/1028

**Comment by UnrealKaraulov** [comment]
@rtxa https://github.com/alliedmodders/amxmodx/pull/1028 is fix for this pull request, for "disable/enable for all plugins", and other fixes. But stil not merged :(

**Comment by UnrealKaraulov** [comment]
> Hi @UnrealKaraulov. Would you mind to explain how this new feature works? I'm using one of the latest commits and I couldn't fail to notice that some of the plugins that I have in debug mode are throwing messages like `[agmodx.amxx] performance issue. Function plugin_init executed more than 100.6ms.`. Can this be disabled without disabling the debug feature in plugins which is useful for other kind of errors?
