### ISSUE TITLE
Is possible to update SQLite Version?

### ISSUE THREAD

**Issue by SmileYzn** [alliedmodders/amxmodx#1030]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).

# Environment
  * Operating System version: Windows / Linux
  * Game/AppID (with version if applicable): 10
  * Current AMX Mod X version: 1.10 dev 5461
  * Current Metamod version: 1.19p38

# Description
Is possible to update SQLite in sqlite module?

There is some improvements and adjusts to match with mondern version of sqlite.

Ie. Some new RETURNING id (From INSERT INTO statement). That  can be used in sqlite 3.35 or newer

``insert into users (first_name, last_name) values ('Jane', 'Doe') returning id;``

Thanks for work!

**Comment by wilianmaique** [comment]
Use 'SQL_GetInsertId' to get last id insert

**Comment by SmileYzn** [comment]
> Use 'SQL_GetInsertId' to get last id insert

RETURNING is used to return any field not only id. 
Also RETURNING is available since sqlite 3.35 not older versions.

Ps. Sqlite 3.35 also has other improvements.

**Comment by wilianmaique** [comment]
I understand what you mean, 'SQL_GetInsertId' works with sqlite too

**Comment by SmileYzn** [comment]
Finally someone made a pull reques to this.
