### ISSUE TITLE
About Compiler

### ISSUE THREAD

**Issue by wilianmaique** [alliedmodders/amxmodx#1055]
Anyone who messes with 'PAWN' for a long time knows about the 'lysis decompiler' 'amxx uncompress'

both serve to 'decompile' at least a little, now the 'amxx uncompress' is possible to edit texts and then recompile and the plugin still works!

I was wondering if there is anything I can do to prevent this? or make it even more difficult.

**Comment by luxxxoor** [comment]
why is that an issue in the first place ?

**Comment by wilianmaique** [comment]
> 

The problem is in being able to modify a code where it was not supposed to be possible, this is a big problem, the idea is to make it even more difficult. We know that those who really know how to 'reverse engineer' it is almost impossible to protect a code.

**Comment by luxxxoor** [comment]
i don't see any benefits in doing that


AMXX is under GNU 3 licence:

The GNU General Public License (GNU, GPL, or GPL) is a free software license originally written by Richard Stallman of the Free Software Foundation, which guarantees that users are free to use, share, and modify the software without paying anyone for it.

**Comment by wilianmaique** [comment]
> i don't see any benefits in doing that
> 
> AMXX is under GNU 3 licence:
> 
> The GNU General Public License (GNU, GPL, or GPL) is a free software license originally written by Richard Stallman of the Free Software Foundation, which guarantees that users are free to use, share, and modify the software without paying anyone for it.

I'm talking about plugins themselves...

**Comment by luxxxoor** [comment]
which are also on the same license

**Comment by wilianmaique** [comment]
> which are also on the same license

if that were the case we would have to see so many things wrong on the internet, but that's not how it works my friend

**Comment by luxxxoor** [comment]
just because people do bad things doesn't mean we have to do it too

**Comment by dvander** [comment]
Per the AMX Mod X license, binaries must have the accompanying source available.
