### ISSUE TITLE
admin_sql.sma is missing

### ISSUE THREAD

**Issue by fred0r** [alliedmodders/amxmodx#1061]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  - [X] I have updated AMX Mod X to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.
  - [X] I have updated AMX Mod X to the [latest snapshot](https://www.amxmodx.org/snapshots.php) and it still happens.
  - [X] I have updated Metamod to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.

# Description

theres no admin_sql.sma available - only the precompiled admin_sql.amxx.
why?

**Comment by Mistrick** [comment]
https://github.com/alliedmodders/amxmodx/blob/9fbf91ded017111f35338dff502882d7049ce1f6/plugins/AMBuilder#L104-L109

**Comment by fred0r** [comment]
> https://github.com/alliedmodders/amxmodx/blob/9fbf91ded017111f35338dff502882d7049ce1f6/plugins/AMBuilder#L104-L109

thank you for explaining.
