### ISSUE TITLE
Apple Build: NASM cert issue with CURL adversely affecting compile

### ISSUE THREAD

**Issue by djearthquake** [alliedmodders/amxmodx#1073]
I've opened a pull for this. It is rather straight forward single line of code fix. It will help a lot since Nasm is required to compile.

**Comment by djearthquake** [comment]
https://github.com/actions/runner-images/issues/7246

Opened issue for the ci.yml Apple OS image needing i386.

**Comment by djearthquake** [comment]
Got a unprofessional response. Good luck regarding image-runners and OSX.

**Comment by dvander** [comment]
Does anyone use the apple builds we have? I'd be fine to sunset them, and users who want them can built on their own. We have super limited capability to test anything.

**Comment by djearthquake** [comment]
Amxx on Darwin is a rare commodity! Some things are just lost to time.

**Comment by dvander** [comment]
I'm not sure whether that statement is advocating for or against keeping the builds :D

**Comment by djearthquake** [comment]
It's acceptance of the inevitable. Keep OSX at least for now. Appveyor = tax write-off. If it has any bearing, Apple owners cross me as more likely to donate money over the non-steamers.
