### ISSUE TITLE
Feature Request: Make the compiler output selectable

### ISSUE THREAD

**Issue by OciXCrom** [alliedmodders/amxmodx#547]
Is it possible to make the text that the compiler outputs selectable? Right now when someone needs to post the errors they got when compiling a plugin, they must post a screenshot or try to write the error manually which is very incovenient. I'm talking about the compile.exe window.

**Comment by WPMGPRoSToTeMa** [comment]
It is just windows console application, so this should help https://stackoverflow.com/questions/6828450/console-application-with-selectable-text.

**Comment by OciXCrom** [comment]
By the way this is not exactly a question :smiley: , I'm asking if it can be implemented in AMXX's compiler for 1.9. I don't know how to do it that so I posted it here instead.

**Comment by rsKliPPy** [comment]
As stated by Prostotema, it's something that depends on your environment (your terminal/command line), not the compiler.

**Comment by OciXCrom** [comment]
I see. I thought it's possible to make it for everyone.

**Comment by WPMGPRoSToTeMa** [comment]
@OciXCrom SO answer states that it is possible.

**Comment by OciXCrom** [comment]
Then someone should make a PR and implement it.

**Comment by justgo97** [comment]
@OciXCrom Its not worth it, a new GUI code must be implemented which means more dependencies and more time in maintaining it you can just use the windows default window as it gets the job done perfectly.

**Comment by WPMGPRoSToTeMa** [comment]
@justgo97 why GUI? It can be implemented with default console window.
