### ISSUE TITLE
Bug with colored menus in Half-Life

### ISSUE THREAD

**Issue by OciXCrom** [alliedmodders/amxmodx#553]
I got a report by a user that runs a Half-Life server that when he updated to AMXX 1.9 this happened with all the menus:

![](https://i.imgur.com/yER56Du.jpg)

If I'm not mistaken, colored menus are not supported in Half-Life. It's probably a mistake made in PR #143. He has been using 1.8.2 before that and the menus worked fine without displaying the color symbols.

I tested as well to make sure - the color symbols appear in menus when using 1.9.0, downgrading to 1.8.2 removes them.

I also noticed another bug while testing the menus. If you leave a menu open and you leave the server, when you come back the menu stays open but you're not able to select anything from it. It happens even if you restart the server.

**Comment by Arkshine** [comment]
Then 'valve' should be removed from the list.
What about tfc and dmc?

**Comment by OciXCrom** [comment]
@Arkshine I don't have those games so I can't really test.

**Comment by Arkshine** [comment]
Tested with HL and TFC, and I see the color:

![image](https://user-images.githubusercontent.com/360640/45189487-8b046080-b239-11e8-9da8-58914aa028f4.png)

**Comment by WPMGPRoSToTeMa** [comment]
dmc supports them https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dmc/cl_dll/menu.cpp#L82-L125.

**Comment by OciXCrom** [comment]
I guess we need to check if the build version is 6xxx before adding these games in the list that supports colored menus.

**Comment by rsKliPPy** [comment]
AMXX only supports the latest build afaik, there's no need for such check.

**Comment by Arkshine** [comment]
We are not going to start to adjust stuff based on game build.
There is no reason to not update his server especially when the latest builds contains security fixes.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine, client build is implied, but anyway AMX Mod X supports only the latest server/client build.

**Comment by Arkshine** [comment]
Yes, you're right.

**Comment by OciXCrom** [comment]
I see, the server that I tested on hasn't been updated for ages. This may be a problem who people that don't know how to update their server, but they will learn eventually.

PS: why did they have to hardcode the colors like that, RGB menus would have been much nicer. :disappointed:

**Comment by Arkshine** [comment]
As stated WPMGPRoSToTeMa, this is a client-side feature, so the server is unrelated here.
