### ISSUE TITLE
About download

### ISSUE THREAD

**Issue by all85100** [alliedmodders/amxmodx#578]
When can I download the collection to the latest pull requests? I want to test it, when will the official version of Amxmodx be released? is the version number 1.9.0 or 1.10.1?

**Comment by gtteamamxx** [comment]
@all85100 
https://www.amxmodx.org/downloads-new.php

**Comment by all85100** [comment]
no,build 5016,not have new pull requests

**Comment by gtteamamxx** [comment]
@all85100 
So, you have to wait when it's been build or build is by yousrelf using AMBuild.

**Comment by Arkshine** [comment]
Latest build for master, meaning 1.10, branch can be downloaded from there https://www.amxmodx.org/downloads-new.php?branch=master

**Comment by OciXCrom** [comment]
@Arkshine So shouldn't this PR (#559) be merged into 1.9 instead as it's a bug fix?

**Comment by Arkshine** [comment]
Yes, planned to do it. Though forgot at some point, or wanted to wait for more PRs, don't remember. Will do now.
