### ISSUE TITLE
The statsx plugin uses the client_print_color function bug

### ISSUE THREAD

**Issue by all85100** [alliedmodders/amxmodx#589]
After modifying the client_print function to the client_print_color function on the statsx plugin, when statsx.txt is used to display the team color in ^3, sometimes the color of the team is normal and sometimes abnormal.
![default](https://user-images.githubusercontent.com/35861556/45759578-ca2faa00-bc5a-11e8-822b-2e0938838e11.png)

**Comment by OciXCrom** [comment]
And how exactly did you "modify" the function? Show your code.

**Comment by all85100** [comment]
sorry,look http://dl.lonzi.cn/cstrike/statsx.sma     
 http://dl.lonzi.cn/cstrike/statsx.txt

**Comment by all85100** [comment]
@OciXCrom I have tried many times and can't succeed. Maybe I won't use this function. Can you find a sample in the code to see an example? Thank you.

**Comment by Arkshine** [comment]
The second param of `client_print_color` is to tell what team color you want to use if you use `^3` in your text.

Instead of `print_chat`, you need to provide instead of those:

`print_team_default`
`print_team_grey`
`print_team_red`
`print_team_blue`

**Comment by Arkshine** [comment]
Closing for now. If you are others questions, feel free to post them.
