### ISSUE TITLE
[SOLVED] Lang Variables Not Working

### ISSUE THREAD

**Issue by HashingTag** [alliedmodders/amxmodx#595]
The following variables in `data/lang/admincmd.txt` is not showing up in the cstrike game chat;
> ADMIN_MAP_1 = ADMIN: changelevel %s
> ADMIN_MAP_2 = ADMIN %s: changelevel %s

I have also tried changing the text to my own in the newest and previous versions of AMX MOD X but the variable value just stays the same as the default one. Maybe I missed something or something is wrong with my server files.

I'm currently running **ReHLDS**;
```
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 10:46:45 Sep 19 2018 (1621)
```

**Comment by Arkshine** [comment]
What do you mean by not "showing up", are you saying after you use `amx_map` command, you see ``ML_NOTFOUND"? Or simply nothing?
If nothing, what is the current value of  `amx_show_activity`?

**Comment by Arkshine** [comment]
Are you testing through the map menu? If so, you change the key in `mapmenu.txt` instead. Yea, it's a bit weird.
