### ISSUE TITLE
amx_addban bug

### ISSUE THREAD

**Issue by Maxi605** [alliedmodders/amxmodx#596]
L 09/22/2018 - 17:05:44: [admincmd.amxx] Cmd: "Server Name <0><><>" ban "" (minutes "ï¿½ï¿½ï¿½") (reason "ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½")

Executed the amx_addban command with no parameters, this happen

This bug is happening on 1.8.2, i'm pretty sure this isn't fixed on 1.9

And executed the command on the server console

**Comment by djearthquake** [comment]
Quote STEAMID. 
amx_ban "steamid" minutes

**Comment by fysiks1** [comment]
If you execute the amx_addban command with no paramters, you will get "Usage:  amx_addban <"authid" or ip> <minutes> [reason]".  Therefore, this is not a bug and is also not possible (as you have described it).
