### ISSUE TITLE
undefined symbol: pow10

### ISSUE THREAD

**Issue by the-swank** [alliedmodders/amxmodx#614]
https://github.com/alliedmodders/amxmodx/blob/0b5584a334a0adb0baaaf5df620f329732f20922/compiler/libpc300/sc2.c#L603
https://github.com/alliedmodders/amxmodx/blob/0b5584a334a0adb0baaaf5df620f329732f20922/compiler/libpc300/sc2.c#L685

**Comment by Freeman-AM** [comment]
Someone should close this @the-swank or @Arkshine 
It's now merged.
