### ISSUE TITLE
Runtime error when using the conditional operator with fmt

### ISSUE THREAD

**Issue by rtxa** [alliedmodders/amxmodx#621]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10 64 Bits
  * Game/AppID (with version if applicable): Half-Life 7561
  * Current AMX Mod X version: 1.8.3 5169
  * Current Metamod version: v1.21p37
# Description
I'm trying to show an empty message in case some condition becomes false, the best think that came to my mind to improve readability is to use the ternary operator, but it shows me a runtime error...

# Problematic Code (or Steps to Reproduce)
Put this code in plugin_init, compile and test it
  ```PAWN
	server_print(id, "%s", true ? fmt("Hello") : "");
  ```

# Logs
[AMXX] Run time error 8: heap low

**Comment by Arkshine** [comment]
We're probably not going to touch the compiler unless there is an official pawn fix about it.

The usage seems suspicious and abusive. What is your concrete usage (full example)?

**Comment by rtxa** [comment]
I use it to show to a player if a match has started, if not, don't show anything.
![](https://imgur.com/u1heqnF.png?raw=true)
![](https://imgur.com/rO6Eal1.png?raw=true)
Without ternary
```PAWN
get_pcvar_string(gCvarContact, arg, charsmax(arg));
formatex(started, charsmax(started), "%L", id, "MATCH_STARTED");
set_dhudmessage(gHudRed, gHudGreen, gHudBlue, 0.05, 0.02, 0, 0.0, 10.0, 0.2);
show_dhudmessage(id, "AG Mod X %s^n%s^n^n%s", VERSION, arg, gVersusStarted ? started : "");
```
With ternary
```PAWN
get_pcvar_string(gCvarContact, arg, charsmax(arg));
set_dhudmessage(gHudRed, gHudGreen, gHudBlue, 0.05, 0.02, 0, 0.0, 10.0, 0.2);
show_dhudmessage(id, "AG Mod X %s^n%s^n^n%s", VERSION, arg, gVersusStarted ? fmt("%L", id, "MATCH_STARTED" : "");
```

**Comment by Arkshine** [comment]
Does it still error with non-empty string? If not, you could use a space, should be okay in your case.
If yes, you can try with `fmt("")`, it's weird, but it's okay, doesn't matter.

It looks like nothing has been fixed on pawn upstream.

**Comment by rtxa** [comment]
"Does it still error with non-empty string?" What do you mean with this?
That's bad :(

**Comment by Arkshine** [comment]
I meant like with a space inside or anything inside. But it looks like it errors too, weird.

**Comment by Arkshine** [comment]
Let's wait for a little. Understanding the compiler is a struggle, personally, I can't do it, nor I have the time to investigate. Maybe someone will.

**Comment by WPMGPRoSToTeMa** [comment]
As I can see that is because memory is conditionally "allocated", but unconditionally "deallocated".

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine 
> It looks like nothing has been fixed on pawn upstream.

Looks like it was fixed a long time ago. `hier13` is already fixed since 2006 (or earlier?): https://github.com/compuphase/pawn/blob/d4fcf64cf26fe52dadaacc0190def195537dd58c/compiler/sc3.c#L1056.

**Comment by WPMGPRoSToTeMa** [comment]
@dvander why didn't you merge [the fix for sourcemod](https://github.com/alliedmodders/sourcemod/commit/c0f7e0b57902001f8a7f8cb05b3484bf68afdf1e) into amxmodx?

**Comment by rtxa** [comment]
@Arkshine I wonder if this hasn't be reverted or overwrited, because I started an old plugin using this function and I'm experiencing again this issues with fmt(), if you need more information I can send you the plugin and test by yourself.
