### ISSUE TITLE
Why there aren't parameters for color2 in set_hudmessage?

### ISSUE THREAD

**Issue by rtxa** [alliedmodders/amxmodx#625]
Why this is hardcoded?
```PAWN
g_hudset.r2 = 255;
g_hudset.g2 = 255;
g_hudset.b2 = 250;
```
And this not?
```PAWN
g_hudset.r1 = static_cast<byte>(params[1]);
g_hudset.g1 = static_cast<byte>(params[2]);
g_hudset.b1 = static_cast<byte>(params[3]);`
```
Code from [here](https://github.com/alliedmodders/amxmodx/blob/c6c4e79b96c5f5b64767da7e8ba9fd3541984450/amxmodx/amxmodx.cpp#L480)

This is specially useful when you set a hud message with effect 2 (Scan Out), the definition is from [here](https://developer.valvesoftware.com/wiki/Game_text)

> Color2 <color255>
    The scanning color for the letter being scanned if the Text Effect keyvalue is set to Scan Out - usually a different shade of Color1.

**Comment by Arkshine** [comment]
I've no idea. Maybe at the very start, there were restrictions on how many params you could have, or maybe the effect colors make no difference?

**Comment by rtxa** [comment]
> 
> 
> I've no idea. Maybe at the very start, there were restrictions on how many params you could have, or maybe the effect colors make no difference?

I have seen some servers that do that in HL1, but I'm sure they use a game_text entity for that, so it works because both of them uses the same UTIL_HudMessage function.
Can this be added by default as the last parameters so it will not interfere with other plugins?

**Comment by justgo97** [comment]
i guess set_hudmessage2 or set_hudmessage_ex can be added ?

**Comment by rtxa** [comment]
Okay thanks, I will try to make a pull request for this.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine should it really be a new native? We can extend `set_hudmessage`.

**Comment by rtxa** [comment]
Yes, I agree with @WPMGPRoSToTeMa,  maybe that function would become a hell because already it has a lot of parameters but making a new function for only that isn't enough reason.

**Comment by justgo97** [comment]
> PD: Maybe it has to be to with the order, the color2 parameters should be on the right of color1 parameters no?

that would break backward compatibility

**Comment by Arkshine** [comment]
Yes, but I would prefer to have a new one with both color side by side and the channel at the very end. It would make more sense and usable this way. You also will force people to write the channel. The point is to keep similar behavior in how you would use the params.

If you guys think it's better to reuse the original native, so be it, but personally, I don't think it's a good thing for the users.

**Comment by rtxa** [comment]
@justgo97 That is my though why @Arkshine wants a new function
I think you are right, is better like that.

**Comment by WPMGPRoSToTeMa** [comment]
> You also will force people to write the channel.

Why? Users can just use dot notation for new color parameters. Or do you mean backward compatibility?

**Comment by Arkshine** [comment]
> Why? Users can just use dot notation for new color parameters. Or do you mean backward compatibility?

I just meant it's more convenient for the users. Most of the coder don't even know you can use the dot notation, and the channel param is rarely used. It's enough a reason for me to have a new native to have the right param order from the start similar to the original.

**Comment by rtxa** [comment]
@Arkshine can you show an example of that?

**Comment by OciXCrom** [comment]
I have a better idea that I tried to develop a while ago but I was stuck at one point.

Instead of using `set_hudmessage` before every `show_hudmessage` function, it would be much better if the message parameters were set only once, for example in `plugin_init`.

To do this, we can add a new HUD message display system that works in a very simple way:

```pawn
/* @return    Unique hudset id */
native hudset_create(red = 200, green = 100, blue = 0, Float:x = -1.0, Float:y = 0.35, effects = 0, Float:fxtime = 6.0, Float:holdtime = 12.0, Float:fadeintime = 0.1, Float:fadeouttime = 0.2, channel = -1, red2 = 255, green2 = 255, blue2 = 255)

/* @param hudset    Unique hudset id created via hudset_create() */
native hudset_show_hud(id, hudset, message[], any:...)

/* @param hudset    Unique hudset id created via hudset_create() */
native hudset_show_dhud(id, hudset, message[], any:...)

native hudset_modify(hudset, Hudset_Params:param, any:value)
```

And so on... More function can be implemented if needed.
Also, if the number of params is too much, we can do this instead:

```pawn
native hudset_create(color[3] = {200, 100, 0}, Float:pos[2] = {-1.0, 0.35}, effects = 0, holdtime = 12.0, fadetime[2] = {0.1, 0.2}, channel = -1, color2[3] = {255, 255, 255})
```

**Comment by rsKliPPy** [comment]
Hudsets (or whatever the name we settle on) seems like a good intuitive solution. You'd want to add tags to that API though, untagged handles should the thing of the past.

**Comment by PM32** [comment]
> I have a better idea that I tried to develop a while ago but I was stuck at one point.
> 
> Instead of using `set_hudmessage` before every `show_hudmessage` function, it would be much better if the message parameters were set only once, for example in `plugin_init`.
> 
> To do this, we can add a new HUD message display system that works in a very simple way:
> 
> ```pawn
> /* @return    Unique hudset id */
> native hudset_create(red = 200, green = 100, blue = 0, Float:x = -1.0, Float:y = 0.35, effects = 0, Float:fxtime = 6.0, Float:holdtime = 12.0, Float:fadeintime = 0.1, Float:fadeouttime = 0.2, channel = -1, red2 = 255, green2 = 255, blue2 = 255)
> 
> /* @param hudset    Unique hudset id created via hudset_create() */
> native hudset_show_hud(id, hudset, message[], any:...)
> 
> /* @param hudset    Unique hudset id created via hudset_create() */
> native hudset_show_dhud(id, hudset, message[], any:...)
> 
> native hudset_modify(hudset, Hudset_Params:param, any:value)
> ```
> 
> And so on... More function can be implemented if needed.
> Also, if the number of params is too much, we can do this instead:
> 
> ```pawn
> native hudset_create(color[3] = {200, 100, 0}, Float:pos[2] = {-1.0, 0.35}, effects = 0, holdtime = 12.0, fadetime[2] = {0.1, 0.2}, channel = -1, color2[3] = {255, 255, 255})
> ```

I agree with this
