### ISSUE TITLE
Compiler throw warning i should return value.

### ISSUE THREAD

**Issue by gtteamamxx** [alliedmodders/amxmodx#629]
On this code
![image](https://user-images.githubusercontent.com/10392319/46903888-4a54d280-cedc-11e8-8a2a-5fbd0ca0e3dc.png)

All path are filled with return and compiler thinks i didn't do that.

Version  1.9.0+5230

**Comment by Arkshine** [comment]
You are not using the latest compiler version.

I believe it has been already fixed.

**Comment by gtteamamxx** [comment]
I'm using latest compiler.

stock const AMXX_VERSION_STR[] = "1.9.0.5230";

**Comment by Arkshine** [comment]
In your screenshot, before you edited, the version showed 1.8.1. You should see 1.9.0 now.

Updating the includes doesn't mean the compiler is updated.
Make sure `amxxpc32.dll` or `amxxpc32.so` is updated as well. And try again.

**Comment by gtteamamxx** [comment]
Yes. You are true. 
I believed in windows .zip explorer is wokring correctly on my insider build but.. 
it copied files but not into target folder. creppy.
I used 7zip and checked. This is fixed right now

Sorry for my mistake

**Comment by Arkshine** [comment]
No problem, glad it's working now.
