### ISSUE TITLE
Problem on AmxModX 1.9 (build 5235)

### ISSUE THREAD

**Issue by likux35** [alliedmodders/amxmodx#649]
Hello AmxModX developers team !

I am very happy that the CS 1.6 game is still under control for many years to come.
I found a bug that only started after I updated AmxModX from 1.8.3 to 1.9 (5235 build).
The problem is that the objects env_laser (lasers) no longer cause any damage. Could you check this and fix this error? I will wait for your answer.

Have a nice day.

**Comment by PM32** [comment]
Maybe an entity handling mistake. Provide the code of the plugin with issues.

**Comment by likux35** [comment]
Its not plugin, I`m talking about laser based on maps.

**Comment by PM32** [comment]
Provide a map with this entity

**Comment by likux35** [comment]
jail_gemesi you can test it. And other maps, lasers not working anymore.

**Comment by likux35** [comment]
Haha lol, now started to work. Close topic.
