### ISSUE TITLE
log_to_file for descending order too.

### ISSUE THREAD

**Issue by Dr-Strange91** [alliedmodders/amxmodx#650]
Hello,
Actually using this native log_to_file
https://dev-cs.ru/amxx/amxmodx/log_to_file/view

Plugin saves files logs in Ascending Order, which means Older one above and newer one below and in this case if there are too much logs, the owner have to drag long down to see the newer logs.

Example:

L 12/**03**/2018 - 21:32:40:
L 12/**04**/2018 - 19:26:49: 
L 12/**05**/2018 - 06:19:58:

why not improving the native or adding a function? which adds logs in descending order too and there should be no need to create stock.

Example:

L 12/**05**/2018 - 19:26:40:
L 12/**04**/2018 - 19:26:49: 
L 12/**03**/2018 - 06:19:58:

I meant ascending and descending functions for both options should be available into AMXX.

# Environment
  * Operating System version:  Linux
  * Game/AppID (with version if applicable): 10 [Counter-Strike 1.6] 
  * Current AMX Mod X version: 1.90 [5235] 
  * Current Metamod version: 1.21p37

**Comment by rsKliPPy** [comment]
Because files don't and can't work like that.

**Comment by rsKliPPy** [comment]
Because files don't and can't work like that. Appending is an easy operation, prepending means copying the whole file each operation.
