### ISSUE TITLE
New public vars for plugin data

### ISSUE THREAD

**Issue by KaidoRen** [alliedmodders/amxmodx#712]
Hi everyone! I have a ready opportunity to do so:
```PAWN
#include <amxmodx>

public stock const PluginName[] = "test";
public stock const PluginVersion[] = "1.0";
public stock const PluginAuthor[] = "Kaido Ren";

public plugin_init()
{
    
}
```

The bottom line is that you don't need to call the register_plugin function.
Before you make a pull request, I would like to clarify whether there is a need for this?

**Comment by voed** [comment]
Good idea. Also it would be great to add "url" variable for support/update link

**Comment by eat1k** [comment]
I agree. It would be a really nice feature.

**Comment by wopox1337** [comment]
also pls add "description"

**Comment by fl0werD** [comment]
Maybe better use "plugin_info_t struct" like metamod or "public Plugin myinfo" like sourcemod?

**Comment by KaidoRen** [comment]
@fl0werD Implement the structs in the compiler - I will do it like this

**Comment by fl0werD** [comment]
@KaidoRen use array

**Comment by KaidoRen** [comment]
This
```PAWN
public stock const PluginInfo[][] = {
    "test",
    "1.0",
    "Kaido Ren"
};
```
 is not equal to this (sm)
```PAWN
public Plugin myinfo =
{
	name = "test",
	author = "Kaido Ren",
	description = "",
	version = "1.0",
	url = ""
};
```

without explicit indication of arguments it looks incomprehensible and ridiculous.

**Comment by fl0werD** [comment]
`plugin_info_t Plugin_info =
{
	META_INTERFACE_VERSION,			// ifvers
	"",				// name
	"",					// version
	"",				// date
	"fl0wer",				// author
	"",	// url
	"visible",				// logtag, all caps please
	PT_CHANGELEVEL,				// (when) loadable
	PT_ANYTIME,				// (when) unloadable
};`

Say it to metamod.

**Comment by KaidoRen** [comment]
@fl0werD there at least a structure, but not a normal array.

**Comment by fl0werD** [comment]
I can advice you to use default args in register_plugin.

**Comment by WPMGPRoSToTeMa** [comment]
@fl0werD you can use [designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers) for `plugin_info_t` structure since C++20.

**Comment by fl0werD** [comment]
@WPMGPRoSToTeMa I think it will added in amxx 3.0

**Comment by fl0werD** [comment]
@KaidoRen if you can't remember arguments you can use
> register_plugin
> (
> 	.plugin_name = "test",
> 	.version = "1.0,
> 	.author = "Kaido Ren",
> };

**Comment by voed** [comment]
@KaidoRen why you closed issue?
