### ISSUE TITLE
1.9.0: Modules and plugins are not loaded

### ISSUE THREAD

**Issue by am1github** [alliedmodders/amxmodx#722]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Gentoo Linux 4.19.23-gentoo
  * Game/AppID (with version if applicable): ReHLDS-3.6.0.671)
  * Current AMX Mod X version: AmxModX-1.9.0-5247)
  * Current Metamod version: ReMetamod-1.3.0.128, API (5:13)
  - [x] I have updated AMX Mod X to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.
  - [x] I have updated AMX Mod X to the [latest snapshot](https://www.amxmodx.org/snapshots.php) and it still happens.
  - [x] I have updated Metamod to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.

# Description
I was upgrading glibc-2.28-r6 to glibc-2.29-r2 and ran into the following problem:
> kernel: traps: hlds_linux[ID] general protection ip:HEX sp:HEX error:0 in libc-2.29.so

After that i was trying to upgrade AmxModX from 1.8.2 to 1.9+, because it seems that this is related to AmxModX or some plugins, while ReHLDS without AmxModX runs fine. While the upgrade to amxmodx-1.9.0-5247 was done, the server get startet but no modules or plugins are loaded. No errors are logged, permissions are fine so far. I tried also uncommenting all modules in modules.ini, but this doesn't change anything. Any hints?

# Logs
> amxx modules
Currently loaded modules:
name                    version     author               status
0 modules, 0 correct

> amxx plugins
Currently loaded plugins:
name                    version     author            file             status
0 plugins, 0 running

**Comment by asherkin** [comment]
Are you using any security modules such as SELinux, AppArmor, or YAMA?

**Comment by am1github** [comment]
No, i don't.

**Comment by Arkshine** [comment]
I've no idea, but can you try to force load a module to see if metamod will output some useful information?

`meta_debug` to 8 for example
Then, `meta load addons/amxmodx/modules/fun_amxx_i386`

**Comment by am1github** [comment]
Alright, sorry for the delay i was trying to check some other things but didn't found any issue.
One time this message was displayed after a mapchange:
>[AMXX] FlagManager: Cannot open file "cstrike/addons/amxmodx/configs/cmdaccess.ini" (FILE pointer null!)

On every mapchange this is displayed:
>[AMXX] Modules list not found (file "addons/amxmodx/configs/modules.ini")

But both files and all others are present and accessible by the running user.

The following structure is given:
>steam@ex41s-ssd / $ ll /opt/steam/cs16/27015/cstrike/addons/amxmodx/modules/
total 6.2M
4.0K drwxrwsr-x 3 steam srvmngr 4.0K May 21 11:45 .
4.0K drwxr-xr-x 9 root  root    4.0K May 15 18:38 ..
4.0K drw-r-Sr-- 2 root  root    4.0K May 15 18:44 182
132K -rwxr-xr-x 1 steam srvmngr 130K May 16 15:12 cstrike_amxx_i386.so
 60K -rwxr-xr-x 1 steam srvmngr  60K May 16 15:13 csx_amxx_i386.so
 96K -rwxr-xr-x 1 steam srvmngr  95K May 16 15:13 engine_amxx_i386.so
312K -rwxr-xr-x 1 steam srvmngr 310K May 16 15:13 fakemeta_amxx_i386.so
 48K -rwxr-xr-x 1 steam srvmngr  48K May 16 15:13 fun_amxx_i386.so
 56K -rwxr-xr-x 1 steam srvmngr  56K May 16 15:13 geoip_amxx_i386.so
452K -rwxr-xr-x 1 steam srvmngr 451K May 16 15:12 hamsandwich_amxx_i386.so
 68K -rwxr-xr-x 1 steam srvmngr  67K May 16 15:12 json_amxx_i386.so
3.4M -rwxr-xr-x 1 steam srvmngr 3.4M May 16 15:12 mysql_amxx_i386.so
 36K -rwxr-xr-x 1 steam srvmngr  36K May 16 15:13 nvault_amxx_i386.so
444K -rwxr-xr-x 1 steam srvmngr 444K May 16 15:12 regex_amxx_i386.so
 20K -rwxr-xr-x 1 steam srvmngr  18K May 16 15:13 sockets_amxx_i386.so
1.1M -rwxr-xr-x 1 steam srvmngr 1.1M May 16 15:12 sqlite_amxx_i386.so

When i manually try loading the modules `mysql, cstrike, fun, engine, fakemeta, geoip, csx, hamsandwich` it succeeds,
>
 [ 7] AMX Mod X               RUN   -    amxmodx.so                v1.9.0.5247     ini  Start ANY
 [ 8] MySQL                   RUN   -    mysql_amxx_i386.so        v1.9.0.5247     cmd  ANY   ANY
 [ 9] CStrike                 RUN   -    cstrike_amxx_i386.so      v1.9.0.5247     cmd  ANY   ANY
 [10] Fun                     RUN   -    fun_amxx_i386.so          v1.9.0.5247     cmd  ANY   ANY
 [11] Engine                  RUN   -    engine_amxx_i386.so       v1.9.0.5247     cmd  ANY   ANY
 [12] FakeMeta                RUN   -    fakemeta_amxx_i386.so     v1.9.0.5247     cmd  ANY   ANY
 [13] GeoIP                   RUN   -    geoip_amxx_i386.so        v1.9.0.5247     cmd  ANY   ANY
 [14] <sockets_amxx_i386.so>  badf load  sockets_amxx_i386.so      v -             cmd   -     -
 [15] <regex_amxx_i386.so>    badf load  regex_amxx_i386.so        v -             cmd   -     -
 [16] <nvault_amxx_i386.so>   badf load  nvault_amxx_i386.so       v -             cmd   -     -
 [17] CSX                     RUN   -    csx_amxx_i386.so          v1.9.0.5247     cmd  ANY   ANY
 [18] Ham Sandwich            RUN   -    hamsandwich_amxx_i386.so  v1.9.0.5247     cmd  ANY   ANY

but for `sockets, regex, nvault` it fails.
>[META] ERROR: dll: Failed query plugin '<sockets_amxx_i386.so>'; Couldn't find Meta_Query(): function not found
[META] ERROR: dll: Failed query plugin '<regex_amxx_i386.so>'; Couldn't find Meta_Query(): function not found
[META] ERROR: dll: Failed query plugin '<nvault_amxx_i386.so>'; Couldn't find Meta_Query(): function not found

FYI: I changed topic and my setup to 1.9.0-5247 only, so it's easier to debug.

Any suggests? Seems while it can't "see" the modules.ini i wouldn't load the modules. But why it can't see it? It's a regular file with all the access needed, even if it's 777. Hum...

**Comment by am1github** [comment]
I made a complete fresh install and for whatever reason the modules and plugins gets loaded even when the permissions are 1:1 with the old installation. Weird.

**Comment by Arkshine** [comment]
Are you still using the same metamod version?

**Comment by am1github** [comment]
Yes.
