### ISSUE TITLE
Lack of ways to download compiled builds from master branch

### ISSUE THREAD

**Issue by Freeman-AM** [alliedmodders/amxmodx#725]
Since the new dev builds page (https://www.amxmodx.org/downloads-new.php), it's no longer possible to download compiled latest builds from the master branch without compiling it yourself.

Is it possible to fix it ?
Thanks.

**Comment by Mistrick** [comment]
https://www.amxmodx.org/downloads-new.php?branch=master

**Comment by psychonic** [comment]
> https://www.amxmodx.org/downloads-new.php?branch=master

That is the correct URL. I'm not sure how/where a link would go if we want one. @Arkshine ?

**Comment by Arkshine** [comment]
Once `1.9` is released, we will have a `Stable Builds` link pointing to `1.9` and `Dev Builds` to `1.10`.
For now, I guess you could temporarily add a link in the `Dev Builds` page, like: "_Are you looking for version 1.10 (master)?_"
Example:
![image](https://user-images.githubusercontent.com/360640/58512603-cc5ce780-819d-11e9-8900-520327dc0735.png)
What do you think? Or whatever the text/location.

Looking at the current activity, It's probably a good idea to release something soon. In the meantime, this band-aid should be enough.

**Comment by Mistrick** [comment]
@Arkshine what do you think to add builds with binlog enabled?

**Comment by psychonic** [comment]
@Mistrick please don't hijack this issue, but feel free to file a separate one if there isn't one for that already.

**Comment by psychonic** [comment]
@Arkshine I added a similar version of that now. If on the snapshots page for a non-stable version that isn't the master branch, it will now print an extra line past the one that shows the link to the stable branch.
