### ISSUE TITLE
get_user_weapon invalid return type

### ISSUE THREAD

**Issue by DarthMan** [alliedmodders/amxmodx#733]
Hello. I noticed that on the game Team Fortress Classic get_user_weapon always returns 0. I did a simple debug in one of my plug-ins and it returned 0. Hope will be fixed in the upcomiung AMXX v.1.10 build.  Using get_ent_data_entity(iID, "CBasePlayer", "m_pActiveItem") works correctly, as it returns the correct weapon entity id, but I don't need the entity id. Instead, I need the weapon id.

**Comment by eat1k** [comment]
Get m_iId after you get the m_pActiveItem ID.

**Comment by DarthMan** [comment]
Yeah, true, but the amxx native is broken and must be fixed as well.

**Comment by DarthMan** [comment]
I am not sure if that's an issue related to the latest TFC beta update, but it probably is because it worked jsut fine in the past.

**Comment by Arkshine** [comment]
It returns 0 if player is not in-game. It's also possible that the value failed to be saved from `CurWeapon` message (don't know if the message has been altered, probably not?)

**Comment by DarthMan** [comment]
[CODE]#pragma semicolon 1

#include <amxmodx>

public plugin_init()
{
    register_clcmd("say /weaponid", "cmd_PlayerWeapon");
}

public cmd_PlayerWeapon(const iID)
{
    client_print(iID, print_chat, "Weapon ID: %d", get_user_weapon(iID));
}[/CODE]

**Comment by DarthMan** [comment]
> 
> 
> It returns 0 if player is not in-game. It's also possible that the value failed to be saved from `CurWeapon` message (don't know if the message has been altered, probably not?)
> 
> Please show how do you test (provide a small working test code).

Also, any ideas why this happens whenever Rage loads a handler?

https://steamuserimages-a.akamaihd.net/ugc/796487268678021185/1B165AD3FDA761460E80C39B1E646E35813FCEFF/

**Comment by DarthMan** [comment]
Oh, I just restarted the server and now it suddently works.
I haven't done any changes, yet, it magically started to work.
Topic can be closed now.

**Comment by DarthMan** [comment]
Problem is not solved.
This seems to happen everytime I register the CurWeapon message,e ven if I'm not doing anything inside the function.

g_hMsgWeapon = get_user_msgid("CurWeapon");
register_message(g_hMsgWeapon, "OnChangeWeaponPlayer_Pre");

**Comment by Arkshine** [comment]
Likely you block the message where you should not. The native relies on this message. If you want a more reliable way, you should use the private data `m_iID` as stated above.

**Comment by DarthMan** [comment]
I checked, it's not blocked. Just by hooking it, that happens.

**Comment by DarthMan** [comment]
> 
> 
> Likely you block the message where you should not. The native relies on this message. If you want a more reliable way, you should use the private data `m_iID` as stated above.
```
#pragma semicolon 1

#include <amxmodx>

public plugin_init()
{
    register_clcmd("say /weaponid", "cmd_PlayerWeapon");

    register_message(get_user_msgid("CurWeapon", "OnChangeWeaponPlayer_Pre");
}

public cmd_PlayerWeapon(const iID)
{
    client_print(iID, print_chat, "Weapon ID: %d", get_user_weapon(iID));
}

public OnChangeWeaponPlayer_Pre(const iMsgID, const iMsgDest, const iMsgEnt)
{

}
```

Try this and see how it works.

**Comment by Arkshine** [comment]
![image](https://user-images.githubusercontent.com/360640/59071037-5a7f4f00-88bd-11e9-8a99-c718eaacfd95.png)

It works..

**Comment by DarthMan** [comment]
Strange, when I applied that code it didn't work for me.

**Comment by DarthMan** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/360640/59071037-5a7f4f00-88bd-11e9-8a99-c718eaacfd95.png)
> 
> It works..

https://imgur.com/a/7D7Hlkg

Any ideas why I get these errors?
It seems to happen everytime Rage loads a handler.
I tried the handlers from the AM website with updated signatures for TFC, except for FireBullets3 cuz it's CS-only, and it seems to crash all the time.

**Comment by HamletEagle** [comment]
> > ![image](https://user-images.githubusercontent.com/360640/59071037-5a7f4f00-88bd-11e9-8a99-c718eaacfd95.png)
> > It works..
> 
> https://imgur.com/a/7D7Hlkg
> 
> Any ideas why I get these errors?
> It seems to happen everytime Rage loads a handler.
> I tried the handlers from the AM website with updated signatures for TFC, except for FireBullets3 cuz it's CS-only, and it seems to crash all the time.

Github issues are not scripting help. You can't just ask questions about whatever problem you are facing. Please stick to the subject of the issue and post questions in the appropriate place.

**Comment by DarthMan** [comment]
Yeah, I know, but if I post in the right section I'll never ever get answers, because only Arkshine and joaquim know the fix and joaquim is long gone from the forum, Arkshine seems busy 24/7, he abrely even has time to fix AMXX issues.

> 
> 
> > > ![image](https://user-images.githubusercontent.com/360640/59071037-5a7f4f00-88bd-11e9-8a99-c718eaacfd95.png)
> > > It works..
> > 
> > 
> > https://imgur.com/a/7D7Hlkg
> > Any ideas why I get these errors?
> > It seems to happen everytime Rage loads a handler.
> > I tried the handlers from the AM website with updated signatures for TFC, except for FireBullets3 cuz it's CS-only, and it seems to crash all the time.
> 
> Github issues are not scripting help. You can't just ask questions about whatever problem you are facing with completely unrelated stuff.
> Please stick to the subject of the issue and post questions in the appropriate place.

Yeah, I know, but if I post in the right section I'll never ever get answers, because only Arkshine and joaquim know the fix and joaquim is long gone from the forum, Arkshine seems busy 24/7, he abrely even has time to fix AMXX issues.

Also, I didn;t think there's anyone else owning a goldsrc server other than me that wants to use Rage. I know that people have 0 interest on it and most stuff that people want can be already achieved with Orpheu, but that's not my case, as I want to hook a function that has vectors as arguments and don't want to use Okapi because I prefer to have the signatures in files, similar to Orpheu.

**Comment by DarthMan** [comment]
Closing the issue as it was fixed with Metamod -P.
