### ISSUE TITLE
create_cvar boundaries can bypassed by Plugin's CVAR menu

### ISSUE THREAD

**Issue by regener** [alliedmodders/amxmodx#735]
Create a cvar with create_cvar with min and max values defined, then change the value from Plugin's CVAR menu inside the Adminmenu.

Example:
`g_rolldelay = create_cvar("rtd_rolldelay", "180.0", FCVAR_SERVER | FCVAR_SPONLY, "RTD Timelimit", true, 60.0, true, 300.0);`

> L 06/05/2019 - 14:26:29: [pluginmenu.amxx] Cmd: "epresmoha<2224><STEAM_0:1:22567694><>" set cvar (name "rtd_rolldelay") (value "30")

I think it should set it to 60 as defined in min_val or am I missing something / doing something wrong? 😄

Workaround I have set up just now:
`new Float:fLimiter = floatclamp(get_pcvar_float(g_rolldelay), 60.0, 300.0)`
`fNextRollTime = g_fLastRollTime[id] + fLimiter;`

**Comment by eat1k** [comment]
Did you check the value of CVar after you've changed it? Write rtd_rolldelay in console after you change it.

**Comment by Arkshine** [comment]
The change is not in real-time. It happens after the cvar has been set.
What you see is the text when you change it the first time. The value should be set back to 60 right after.

Possible improvement in this plugin would be to check if the cvar has bounds before setting it.

**Comment by regener** [comment]
My bad, it does work of course, but users with defined flag can use the RTD command faster than normal users. (This has been abused by some admins that caused players telling me about the lower roll delays. - Just removed that advantage for safety now.)

Thank you for the answers 😄
