### ISSUE TITLE
[Feature Request] Pre-precache cvars

### ISSUE THREAD

**Issue by OciXCrom** [alliedmodders/amxmodx#736]
Is it possible to add the option to read specific cvars in or before `plugin_precache`? Right now they are read afterwards, I believe in `plugin_cfg`, so it's not possible to use cvars for stuff that need precaching.

For example, if I have a plugin that uses a specific sound, I want to make the sound changeable via cvar, rather than forcing the end-user to modify the .sma file or create an entire .ini file just for one sound.

One way to do this is, for example, adding an optional argument in the `create_cvar` function:

```pawn
native create_cvar(..., bool:precache = false);
```

If this argument is set to `true`, the cvar will be read in `plugin_precache`, otherwise it will read it in `plugin_cfg` like it is right now.

**Comment by Arkshine** [comment]
You can call `EngFunc_Precache[Model|Sound|Generic` in `plugin_init`/`plugin_cfg` and then doing all your config there instead.

**Comment by OciXCrom** [comment]
I wasn't aware of that method. Thanks.
