### ISSUE TITLE
Structures in pawn

### ISSUE THREAD

**Issue by 4D1G06** [alliedmodders/amxmodx#737]
In C/C++/C# we have structures, which are used to store one or more data per object. But we don't in Pawn, and so I came here to ask will it ever be implemented in Pawn? There's a tutorial on how to make "fake structures" (https://forums.alliedmods.net/showthread.php?t=26634), but I'm sure that it takes so much memory compared to structs.
Back to C-languages, you can even do similar statements using enumerations, and this also, unfortunately, impossible in Pawn.

Thanks!

**Comment by rsKliPPy** [comment]
It doesn't take more memory than a real struct implementation would.
