### ISSUE TITLE
get_user_origin should accept float value

### ISSUE THREAD

**Issue by justgo97** [alliedmodders/amxmodx#741]
currently get_user_origin function only accept integer vector 

`native get_user_origin(index, origin[3], mode = 0);`

it should be change to allow float vector or a new function should be created for this purpose

**Comment by afwn90cj93201nixr2e1re** [comment]
IVecFVec?

**Comment by Mistrick** [comment]
> IVecFVec?

And you lost data by dot.

**Comment by afwn90cj93201nixr2e1re** [comment]
so, with user origin isn't important.

**Comment by justgo97** [comment]
@afwn90cj93201nixr2e1re 
Why the extra trouble when we can have a perfect native ?
origins are made to be floats

**Comment by afwn90cj93201nixr2e1re** [comment]
Yep. It's vector, and must be float. And we should have get_user_originf like write_byte and etc functions. Now you can workaround with getting pdata with fakemeta module.
