### ISSUE TITLE
Compiler crashes

### ISSUE THREAD

**Issue by 4D1G06** [alliedmodders/amxmodx#744]
I'm running AMXX 1.9 with the `1.9.0.5241` compiler.
But it seems to crash when using named enumerations within constant headers, for example this will not compile (crashes):
**afile.inc** : 
`#include <afile_const>`

**afile_const.inc** :
`enum Name { a,b,c }`

But if I do this instead:
**afile_const.inc** : 
`enum { a,b,c }`
Nothing happens, any ideas why? Is this a bug or is purposefully intended to? Thanks.

**Comment by eat1k** [comment]
It works fine for me.

**Comment by 4D1G06** [comment]
What's your compiler version?

**Comment by eat1k** [comment]
> What's your compiler version?

I tried on `1.10.0.5257` and `1.9.0.5249`

**Comment by Arkshine** [comment]
It should not crash, but make sure `Name` is not being used by something else?

**Comment by 4D1G06** [comment]
I checked that and it seems to be fixed now, thanks Arkshine :+1: !
