### ISSUE TITLE
Download latest AMXX build (master & 1.9) using terminal

### ISSUE THREAD

**Issue by CrXane** [alliedmodders/amxmodx#748]
Is there any way to download the latest version of 1.9 or master version from a straight zip file that autoupdates everytime something new adds up? Besides copying the download url address from https://www.amxmodx.org/downloads-new.php ,
could we actually use:
`wget http://www.amxmodx.org/amxxdrop/1.9/amxmodx-latest-base-linux(.zip)` &
`wget https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux(.zip)`

**Comment by asherkin** [comment]
There are files on the dropsite that contain the filename of the latest archive.

https://www.amxmodx.org/amxxdrop/1.9/amxmodx-latest-base-linux

**Comment by CrXane** [comment]
The way I came up with:
`wget https://www.amxmodx.org/amxxdrop/1.9/amxmodx-latest-base-linux
cat amxmodx-latest-base-linux`
Manually copy the text
`wget https://www.amxmodx.org/amxxdrop/1.9/<paste text>`

**Comment by Th3-822** [comment]
It can be done directly, like this:
`wget 'https://www.amxmodx.org/amxxdrop/1.9/'$(wget -q -O - 'https://www.amxmodx.org/amxxdrop/1.9/amxmodx-latest-base-linux')`
