### ISSUE TITLE
get_user_team returns wrong team ID

### ISSUE THREAD

**Issue by GasmoN** [alliedmodders/amxmodx#757]
Case 1:
When server starts (after it was stopped), and some player join in the server and spawn, if he die and change his team while he is still dead, the return value of get_user_team(id) native will be -1 until he spawn again.

Case 2: If player disconnects from the server, and server changes the map, and then player join again, if he die and change his team the return value of get_user_team(id) native will be 0 until he spawn again.  

NOTE: This happends only when player join the server for the first time since server was started or map was changed. "Case 2" won't happend if player was on the server while map was changed.

I uploaded video so you can understand better what I am talking about. 
Video is showing only case 1.

Video: https://youtu.be/otMWW-S0Yxo

**Comment by justgo97** [comment]
are you using the original hlds or rehlds / regamedll ?

**Comment by GasmoN** [comment]
> are you using the original hlds or rehlds / regamedll ?
It's original HLDS

**Comment by ClaudiuHKS** [comment]
Good job man I hope it's going to be fixed soon!

**Comment by rsKliPPy** [comment]
Just use `cs_get_user_team`. As far as I know, `get_user_team` is based on the `TeamInfo` message.

**Comment by ClaudiuHKS** [comment]
It is but as they described in their first reply there are some problems.

get_user_team won't match the .inc documentation for example and can cause bugs in some plugins ( perhaps game mode related like CSDM, ZP, .. ).

**Comment by GasmoN** [comment]
> Just use `cs_get_user_team`. As far as I know, `get_user_team` is based on the `TeamInfo` message.

Yes it is based on TeamInfo, but it's a bug and need to be fixed so I posted it here.
Also, I use cs_get_user_team but in colorchat include I have get_user_team is used so it making me big problems when it need to print message in "Case 1" and "Case 2".

**Comment by eat1k** [comment]
> > Just use `cs_get_user_team`. As far as I know, `get_user_team` is based on the `TeamInfo` message.
> 
> Yes it is based on TeamInfo, but it's a bug and need to be fixed so I posted it here.
> Also, I use cs_get_user_team but in colorchat include I have get_user_team is used so it making me big problems when it need to print message in "Case 1" and "Case 2".

client_print_color

**Comment by Arkshine** [comment]
I guess it happens because the team name is not yet registered.

For reference, `get_user_team()` is based on the `TeamInfo` and `ScoreInfo` client messages.

`TeamInfo` is used to register the provided team name.
`ScoreInfo` is used to associate the provided team index to the previously registered name.

This means: if you start the server, you spawn alone as Terrorist, die, then change team to CT ; `ScoreInfo` has yet to be called at spawn, and if you call the native before, you will get -1.

There is this [plugin](https://forums.alliedmods.net/showthread.php?t=137996) which fixes this situation. What it does is basically hook when `TeamInfo` is called, then if the team index from `get_user_name` doesn't match the `m_iTeam` offset ; it sends an extra `ScoreInfo` emessage so AMXX can register the team.

To fix that issue in core, I guess there is no choice but to use `m_iTeam` offset as well (without the extra `ScoreInfo` of course).

One thing I'm not sure though, is it specific to CS?

**Comment by fysiks1** [comment]
I just tested (looping with get_user_team printed to the server console at at 0.5 second intervals) on Day of Defeat.  When you join the server, it returns 0.  When I join Allies I get 1 and when I join Axis I get 2.  If I die and switch teams immediately the result changes from 1 to 2 nearly immediately after pressing the button to switch teams (before I spawn on the other team).

If you need better testing then maybe someone could create a plugin that gathers the data that you need to verify.

**Comment by GasmoN** [comment]
> I guess it happens because the team name is not yet registered with the proper index.
> 
> For reference, `get_user_team()` is based on the `TeamInfo` and `ScoreInfo` client messages.
> 
> `TeamInfo` is used to register the provided team name.
> `ScoreInfo` is used to associate the provided team index with the previously registered name.
> 
> This means: if you start the server, you spawn alone as Terrorist, die, then change team to CT ; `ScoreInfo` has yet to be called at spawn, and if you call the native before, you will get -1.
> 
> There is this [plugin](https://forums.alliedmods.net/showthread.php?t=137996) which fixes this situation. What it does is basically hook when `TeamInfo` is called, then if the team index from `get_user_name` doesn't match the `m_iTeam` offset ; it sends an extra `ScoreInfo` emessage so AMXX can register the team.
> 
> To fix that issue in core, I guess there is no choice but to use `m_iTeam` offset as well (without the extra `ScoreInfo` of course).
> 
> One thing I'm not sure though, is it specific to CS?

I think it should be fixed in core, at least with the method used in that plugin. 
After all, it's core bug, so it's good to have all core bugs fixed in the core and not in seperated plugins.
