### ISSUE TITLE
Update TFC offsets in gamedata config files

### ISSUE THREAD

**Issue by Arkshine** [alliedmodders/amxmodx#767]
> 
> 
> Please keep content related only to the actual issue. I've already created one in #765.

Ok sure. just wanted to make you sure that u'll see the message. I am not sure if it was added yet in the stable Half-Life build, but TFC got an update last week which includes the fixes and the new member. By the way, it's just 1 offset that was added. So all you have to do is add +4 to everything derived from CBaseMonster and add the new offset.

_Originally posted by @DarthMan in https://github.com/alliedmodders/amxmodx/issues/754#issuecomment-543298924_

**Comment by Arkshine** [comment]
@DarthMan Please check again latest build (don't forget to stop the server) and let me know how it goes.

**Comment by DarthMan** [comment]
> 
> 
> @DarthMan Please check again latest build (don't forget to stop the server) and let me know how it goes.

Works perfect with latest AMXX 1.10 dev build. Thanks !
