### ISSUE TITLE
Loaded plugin 'GeoIP': GeoIP v1.9.0.5258 Sep 10 2018, AMX Mod X Dev Team

### ISSUE THREAD

**Issue by djearthquake** [alliedmodders/amxmodx#768]
1.9.0 does not poll longitude and latitude. [My issue was haphazardly closed 4 days ago.](https://github.com/alliedmodders/amxmodx/issues/691)

This is the checksum of a good working module that works error-free from 1.8.3.
Good (Dec 5th 2018)
557e0b489a5bc03fc8c972ad64da4f7e  geoip_amxx_i386.so

**Comment by Arkshine** [comment]
Did you test the latest 1.9 or master build?

The database file was not properly extracted from the archive before.
To fix, you had to download the latest version directly from official site. Now, the file should be fixed in the package.

**Comment by Arkshine** [comment]
Your comment was closed because I assumed it was related to the database extraction issue.

Did you stop your server before updating the file?
Will give a try.

**Comment by Arkshine** [comment]
@djearthquake I tried under windows with the GeoIP City database, and it works:

![image](https://user-images.githubusercontent.com/360640/67122333-d97e7f80-f1ed-11e9-97e4-d3908497a902.png)

**Comment by djearthquake** [comment]
That's refreshing. The Linux version is what needs attention then please.

**Comment by Arkshine** [comment]
@djearthquake 

I've found the issue.

In short, a behavior change happened in the GeoIP library there https://github.com/maxmind/libmaxminddb/commit/a280aebce2771c12be00a5bdd1aa8ba0c61fab2b. Basically, they moved an essential check (for linux) to their configuration tool that we don't use (we are compiling the library with AMBuild). As result, the values extracted from the database are wrongly converted.

Will try to make a PR today.
