### ISSUE TITLE
TFC HL Events on Amxx1.8.2 - 1.9.0 are missing 

### ISSUE THREAD

**Issue by djearthquake** [alliedmodders/amxmodx#769]
I had to hard-core events to make plugin work on TFC.
_For example I had to use 124 instead of ResetHUD._
https://forums.alliedmods.net/showpost.php?p=2669214&postcount=21

Also "Amx_show_activity" is null on TFC.

Testing was done on Linux Amxx versions: 1.8.2, 1.8.3, and 1.9.0. All of which with and without TFC add-on package. I tried multiple events and it is safe to say many if not all are missing.

**Comment by DarthMan** [comment]
You're probabky doing something wrong. It works fibe for me.

**Comment by Arkshine** [comment]
Usually this kind of error as stated by DarthMan is from a misconfiguration.
Please provide more details about your installation (liblist.gam, metamod config file, plugins used, etc.).

**Comment by djearthquake** [comment]
Liblist.gam was the problem in my case. Thank you both. The bug report only happened when another user was complaining plugins were not working on TFC(which I never use) then when I downloaded it made that rookie mistake in haste evidently to coming here.
