### ISSUE TITLE
Console print has no carriage return on Linux Gearbox build 5260

### ISSUE THREAD

**Issue by djearthquake** [alliedmodders/amxmodx#773]
Console print does not have a carriage return at the end of each line on Linux mod Gearbox.
All the print is bunched together as a hard-to-read paragraph instead of lines.

**Comment by kraasimir** [comment]
I have the same problem. I've been looking at what the bug might be and it's the module of the amxx "addons/amxmodx/dlls/amxmodx_mm_i386.so"
