### ISSUE TITLE
No newline in console!

### ISSUE THREAD

**Issue by Karaulov** [alliedmodders/amxmodx#774]
`----- List of loaded plugins ----- Names of version Author file Compost Anti Fullupdate S 2.0 Pike fullupdatefix.a running ReAimDetector API 0.2.2 ReHLDS Team reaimdetector.a running AMXBans: Core Gm 1.6 Larte Team amxbans_core.am running FreshBans 1.3.6 kanagava fresh_bans_136. running Rechecker Log 0.1 F @ nt0M rc_log.amxx running Teleport Menu 1.10.0.538 AMXX Dev Team telemenu.amxx running Mode 2x2 1.9 s1lent mode.amxx running Gag Me 2.3.4 Radius gag_me.amxx running Fix AutoBuy Bug 1.1 PomanoB & UFPS.T autobuyfix11.am running Admin Commands 1.10.0.538 AMXX Dev Team admincmd.amxx running Only 10 plugins, 10 of them running ----- List of available commands from 1 to 10. Total teams - 62 --------- - Write 'amx_plugins 11 "to continue ----- #

`

but need

-```
---- List of loaded plugins ----- 
Names of version Author file Compost 
Anti Fullupdate S 2.0 Pike fullupdatefix.a running
 ReAimDetector API 0.2.2 ReHLDS Team reaimdetector.a running
 AMXBans: Core Gm 1.6 Larte Team amxbans_core.am running
 FreshBans 1.3.6 kanagava fresh_bans_136. running
 Rechecker Log 0.1 F @ nt0M rc_log.amxx running
 Teleport Menu 1.10.0.538 AMXX Dev Team telemenu.amxx running
 Mode 2x2 1.9 s1lent mode.amxx running
 Gag Me 2.3.4 Radius gag_me.amxx running
 Fix AutoBuy Bug 1.1 PomanoB & UFPS.T autobuyfix11.am running
 Admin Commands 1.10.0.538 AMXX Dev Team admincmd.amxx running
 Only 10 plugins, 10 of them running
 ----- List of available commands from 1 to 10. Total teams - 62
 --------- - Write 'amx_plugins 11 "to continue ----- #

```

**Comment by Arkshine** [comment]
What game?

**Comment by Karaulov** [comment]
Latest AMX 1.10 (from master)
CS 1.6 russian

**Comment by Karaulov** [comment]
With 1.8.3 no problem with newlines

**Comment by Arkshine** [comment]
It's a side-effect of  #763.
It seems newlines are stripped for `TextMsg` this way. Note that AMXX inserts always a new line before sending the message.

This means, either I revert this change or the game needs to be fixed to allow newlines (I've asked mikela-valve here: https://github.com/ValveSoftware/halflife/issues/2611#issuecomment-546274447)

**Comment by Karaulov** [comment]
@Arkshine 
Also with amx_who, etc 
No newlines :(

**Comment by Arkshine** [comment]
To be exact, it seems only the newline at the end of string is stripped.
New lines in the middle of a string still work.

For now, will wait a bit mikela-valve's answer. If I don't see answer today, I will revert #763 until game is fixed.

**Comment by Karaulov** [comment]
@Arkshine impossible to just add newline symbol to endline ?

**Comment by Arkshine** [comment]
It's possible to add another one yes. Doing `Message here\n\n` ; the last `\n` is stripped by the game and the first `\n` will be interpreted as expected.

However this is not normal and there is likely a bug in the game. The last `\n` should not be stripped.
Will wait mikela-valve's answer first. If really nothing happens, I may consider using double-newline then.
