### ISSUE TITLE
"Warning 225: unreachable code" in amxmisc.inc

### ISSUE THREAD

**Issue by FEDERICOMB96** [alliedmodders/amxmodx#782]
This error appears from some version of AMX [1.8.3] (that I don't remember now 😅) to latest build 1.9/1.10

# Problematic Code (or Steps to Reproduce)
https://github.com/alliedmodders/amxmodx/blob/76378fd5d0083986bf1328cd3b9afdd8c885c9b5/plugins/include/amxmisc.inc#L755-L770

# Logs
> amxmisc.inc(769) : warning 225: unreachable code

# Fix
```PAWN
stock constraint_offset(low, high, seed, offset)
{
	new numElements = high - low + 1;
	offset += seed - low;

	if (offset >= 0)
	{
		return low + (offset % numElements);
	}

	return high - (abs(offset) % numElements) + 1;
}
```

**Comment by Reshiramboy** [comment]
close the orto kpo
