### ISSUE TITLE
[Ricochet] Can't select menu options / Can't detect when user executes slot[n]

### ISSUE THREAD

**Issue by LucesEnBabel** [alliedmodders/amxmodx#783]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian GNU/Linux 9.3 (stretch) x86_64
  * Game/AppID (with version if applicable): 
```
Protocol version 48
Exe version 1.1.2.1/Stdio (ricochet)
Exe build: 15:17:26 Jul 24 2019 (8308)
```

AppID: 60
  * Current AMX Mod X version: AMX Mod X 1.9.0.5263
  * Current Metamod version: Metamod v1.21p37  2013/05/30 (5:13)
  - [ ] I have updated AMX Mod X to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.
  - [x] I have updated AMX Mod X to the [latest snapshot](https://www.amxmodx.org/snapshots.php) and it still happens.
  - [ ] I have updated Metamod to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens. 

# Description
Basically, Menu selection and any command bound to any of the slot[n] commands doesn't work.

# Problematic Code (or Steps to Reproduce)
  ```PAWN
public plugin_init()
{
    [...]
    register_clcmd("slot1", "slot_callback");
    register_clcmd("slot2", "slot_callback");
    register_clcmd("slot3", "slot_callback");
    register_clcmd("slot4", "slot_callback");
    register_clcmd("slot5", "slot_callback");
    register_clcmd("slot6", "slot_callback");
    register_clcmd("slot7", "slot_callback");
    register_clcmd("slot8", "slot_callback");
    register_clcmd("slot9", "slot_callback");
    register_clcmd("slot10", "slot_callback");
}

public slot_callback(id)
{
    console_print(id, "callback, this means it's working");
    return PLUGIN_CONTINUE;
}
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by Mistrick** [comment]
You can't hook client-side commands.
For menu `slot*` transformed to `menuselect #num#`.
