### ISSUE TITLE
cssdk_const.inc(1307) : error 020: invalid symbol name ""

### ISSUE THREAD

**Issue by Karaulov** [alliedmodders/amxmodx#786]
D:\CounterStrike\Server\cs_16_server\cstrike\addons\amxmodx\scripting\include\cssdk_const.inc(1307) : error 020: invalid symbol name ""

**Comment by Mistrick** [comment]
AMXX doesn't have this include. It is part of ReAPI module.

**Comment by Karaulov** [comment]
thanks
