### ISSUE TITLE
%s in print_center

### ISSUE THREAD

**Issue by Karaulov** [alliedmodders/amxmodx#787]
Any plugin wrote "%s" instead text at client_print (id,print_center,"%s","asdfasdfasdfasdf")

AMXMODX latest developer build (1.10)

**Comment by fant1kua** [comment]
AmxModx doesn't support non official game client (known as non-steam). It's not a bug.

**Comment by Karaulov** [comment]
@fant1kua > AmxModx doesn't support non official game client (known as non-steam). It's not a bug.

Yes I test some non steam clients. And "restrict weapon menu" too wrote %s instead of text. 

Possible to fix it via plugin ? Server uses "reunion" to get more players (steam players less than non-steam in 100-500 times)

**Comment by kraasimir** [comment]
This: http://www.dedicated-server.ru/vbb/showthread.php?t=27127

**Comment by Arkshine** [comment]
AMXX is required to follow the latest game changes. Note also that those specific changes (#763, #778, https://github.com/alliedmodders/amxmodx/commit/4f6b779bf445f7709c528c8c34f6ea9e0fc7d35d) provides better security.

We don't support non official game builds. 

If you still want to use AMXX 1.9/1.10, there is still the possibility to recompile AMXX without thoses changes.

**Comment by Karaulov** [comment]
@Arkshine it can crash nonsteam clients?

**Comment by Karaulov** [comment]
> @Arkshine it can crash nonsteam clients?

You can add option to disable this changes? (Like 'use_deprecated_print_center'

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine edit your comment
At this line: `We don't support non official game builds.` -> `We don't support nor non official nor not latest game builds.`

Coz steam support build replacing, so, we can just change build to 7960 and it's gonna be official too, xD.

**Comment by Arkshine** [comment]
Sure. I've edited.
