### ISSUE TITLE
register_forward not works for AMXX functions?

### ISSUE THREAD

**Issue by Karaulov** [alliedmodders/amxmodx#796]
```
	register_forward( FM_MessageBegin, "CMessages__MessageBegin_Pre", ._post = false );
	register_forward( FM_WriteString, "CMessages__WriteString_Pre", ._post = false );

```
I can't hook MessageBegin/FM_WriteString/etc functions used in AMXX code to block or replace messages  ?

**Comment by WPMGPRoSToTeMa** [comment]
Only e* (e.g. `emessage_begin`, `ewrite_string`) versions of these functions are hookable.

**Comment by Karaulov** [comment]
@WPMGPRoSToTeMa what need write in register_forward to hook these functions ? (for example for plugin to fix non steam CENTER MSG )

**Comment by afwn90cj93201nixr2e1re** [comment]
As he said you cant hook non e* messages via using register_forward.
You should write a module, which gonna hook it.

**Comment by Karaulov** [comment]
> As he said you cant hook non e* messages via using register_forward.
> You should write a module, which gonna hook it.

@afwn90cj93201nixr2e1re need add support hook this funcion!! (((

**Comment by afwn90cj93201nixr2e1re** [comment]
Ты идиот? Как ты иначе будешь хукать это если это буквально напрямую в движок отправляется?

**Comment by afwn90cj93201nixr2e1re** [comment]
Пиши модуль если тебе это нужно, уже многие реализовали для себя, так как действительно не удобно то что нет поддержки старых клиентов.

**Comment by xLeviNx** [comment]
How about we stick to English here eh?
Translated it, love the commentary.

**Comment by Karaulov** [comment]
@xLeviNx  Impossible to use intercepted message functions in amxx?

**Comment by Arkshine** [comment]
An answer has been provided. Closing the issue.

**Comment by Karaulov** [comment]
@Arkshine answer?? You can't add hook amx messages feature??
