### ISSUE TITLE
read_data does not work in multiforward | amxx 1.8.3

### ISSUE THREAD

**Issue by MatiasEsf** [alliedmodders/amxmodx#802]
Hello 
In versions higher than 1.8.2 the read_data function does not work or is not detected in a multi forward of a register_message

I have no problem looking for an alternative, but I have many plugins (already compiled, I don't have the sma file to modify them) that use this function.

This is the only thing that prevents me from upgrading to a more recent version of amxx.

Any solution?

Plugins use the this function (code extracted from the plugin compiled with lysis, maybe it is not complete ... but its code is this);

```
register_message(get_user_msgid( "Charge"), "Charge")

coreClassExtensions[ClassExtensionCTR][374] = CreateOneForward(plugin, "@ClassCharge", 0);

public Charge(ID, DEST, Client)
{
	new var1;
	if (!is_user_connected(Client) || coreClient[Client][0] < 0)
	{
		return
	}
	if (0 < coreClassExtensions[coreClient[Client][0]][374])
	{
		ExecuteForward(coreClassExtensions[coreClient[Client][0]][374], FWD_Return, Client);
	}
	return
}



```

multiforward in inc (It is a function that all the plugins I have used, the inc is the only thing I have of them)

```
public @ClassCharge ( Client )
{
	static ChargeWEAPON[ 32 ], Entity, Charge;

	getClientWEAPONNAME( Client, ChargeWEAPON );
	
	if ( read_data( 1 ) )
	{
                //functions here
		//but dont work
        }
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
https://wiki.alliedmods.net/Half-life_1_game_events

**Comment by MatiasEsf** [comment]
> https://wiki.alliedmods.net/Half-life_1_game_events

dont is half life D; is other mod

**Comment by afwn90cj93201nixr2e1re** [comment]
meta game output.

What is the mod name?

**Comment by Giferns** [comment]
read_data() is for events
get_msg_arg_... is for messages

**Comment by afwn90cj93201nixr2e1re** [comment]
As Giferns said you should use another one for getting right arg.

**Comment by Arkshine** [comment]
* `register_event`  (post event) -> `read_arg*` natives

![image](https://user-images.githubusercontent.com/360640/69497114-99d84100-0ed9-11ea-976d-9eb676a44a11.png)


* `register_message` (pre event) -> `get_msg_arg*` natives

![image](https://user-images.githubusercontent.com/360640/69497104-701f1a00-0ed9-11ea-98aa-8b3e30fd67f7.png)
