### ISSUE TITLE
amx_showrcon blocked by last update

### ISSUE THREAD

**Issue by GoRiLliAz** [alliedmodders/amxmodx#803]
# Help us help you
  - say in console amx_showrcon status réponse 

> ] amx_showrcon status
> rcon_password is a privileged variable
> Could not execute privileged command rcon status

**Comment by voed** [comment]
There's no solution to fix this. Just type your password manually.
I guess this command should be removed.

**Comment by GoRiLliAz** [comment]
Ok, Thx

**Comment by Arkshine** [comment]
@voed Did not follow really the changes on Github, is the intended behavior that the command is still not allowed after `cl_filterstuffcmd 1`?

**Comment by voed** [comment]
@Arkshine looks like here https://github.com/ValveSoftware/halflife/issues/2581#issuecomment-512909946
