### ISSUE TITLE
set_user_frags not works

### ISSUE THREAD

**Issue by Karaulov** [alliedmodders/amxmodx#804]
cs_set_user_deaths(id,0) - reset deaths

but set_user_frags(id, 0) - not reset kills!!! why ? Please fix this function!

**Comment by regener** [comment]
Not even at round end?

**Comment by Giferns** [comment]
Probably the problem is in the lack of sending a 'ScoreInfo' message

**Comment by afwn90cj93201nixr2e1re** [comment]
btw we shouldnt send it by default, expected, but @Arkshine can add one more option something like .force = 0 - for ScoreInfo updating, yes.

**Comment by Karaulov** [comment]
Yes please if possible, add cs_set_user_frags function, reset in real time as in cs_set_user_deaths

**Comment by Arkshine** [comment]
`cs_set_user_deaths` actually by default sends a `ScoreInfo` message.
What you can do if you are using both natives, is to call first `set_user_frags` then `cs_set_user_deaths`.

**Comment by Karaulov** [comment]
Strange(
