### ISSUE TITLE
Sql explaining

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [alliedmodders/amxmodx#811]
https://github.com/alliedmodders/amxmodx/blob/0ccba6700665e9369f85bc56b0ccae4ff4415f19/modules/sqlite/threading.cpp#L418
Which called from: https://github.com/alliedmodders/amxmodx/blob/2559fcf00aecb19fb6e6f8de846ae37cbcd6d572/modules/sqlite/basic_sql.cpp#L427

So and SQL_FieldNumToName: https://github.com/alliedmodders/amxmodx/blob/2559fcf00aecb19fb6e6f8de846ae37cbcd6d572/modules/sqlite/basic_sql.cpp#L378
And SQL_IsNull and SQL_ReadMoreResult: https://github.com/alliedmodders/amxmodx/blob/2559fcf00aecb19fb6e6f8de846ae37cbcd6d572/modules/sqlite/basic_sql.cpp#L216

Why there is different ways?

I rly don't get why sometime you just casting to unsingned int but otherwise in SQL_FieldNameToNum which is like same as others you going to iterate each array instead just casting, what's wrong? Is that just typo? Or what?

**Comment by dvander** [comment]
Questions about the source are better asked on IRC or the forums, since this doesn't seem like a bug report or issue. There is a slightly higher cost to accessing fields by name, thus both methods are exposed.

**Comment by afwn90cj93201nixr2e1re** [comment]
Bail, you still doesnt asked why its using iteration instead casting? As you said casting - faster, why this method use slow and useless iteration instead just casting and returning value? Isn't faster: cast, iterate, if int founded return true, if not exists return false instead getting chars value on each item?

**Comment by afwn90cj93201nixr2e1re** [comment]
And one more question, how we should use 64 bits (for example mysql int, which gonna save player damage) inside pawn? Now we can't process it without extra columns inside mysql table(damage1, damage2...) which are also unsigned int 32. We need any suggestions, of course we cant just write module and support it for ourselves, but that's not nice.

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine few words.
