### ISSUE TITLE
Invalid cycles ?

### ISSUE THREAD

**Issue by mbto** [alliedmodders/amxmodx#817]
Hello, check this - i think it's invalid cycles

https://github.com/alliedmodders/amxmodx/blob/2559fcf00aecb19fb6e6f8de846ae37cbcd6d572/amxmodx/CLang.cpp#L104

https://github.com/alliedmodders/amxmodx/blob/2559fcf00aecb19fb6e6f8de846ae37cbcd6d572/amxmodx/debugger.cpp#L623

**Comment by dvander** [comment]
Looks fine to me, what do you think is invalid?

**Comment by mbto** [comment]
Condition must be i >= 0, for prevent index out of bound exception.

**Comment by dvander** [comment]
`i >= 0` is always true because `size_t` is unsigned.
