### ISSUE TITLE
Latest build crashing on Linux

### ISSUE THREAD

**Issue by 4D1G06** [alliedmodders/amxmodx#828]
Few hours ago I installed Metamod (**1.20**) and then AMXX (**1.9 - build 5263**). But to my surprise, the game seemed to crash when starting a local server. After some time of troubleshooting, I decided to install the latest (**1.8.2**) stable version of AMXX along with Metamod (**1.21am**) to see the outcome, and it actually worked. I am 90% sure this happened because of base AMXX plugin for MM (**amxmodx_mm_i386.so**) which is seemingly corrupted.
Please review the latest build.

**Comment by xLeviNx** [comment]
Any error logs?

**Comment by 4D1G06** [comment]
Nope.

**Comment by 4D1G06** [comment]
I am sorry for my inconvenience, but the problem was somewhere else, particularly on Metamod (for some weird reason, probably because of **"metamod.dylib"**). I am closing this issue with the hope of being the last one! ^^
