### ISSUE TITLE
Regarding the miscstats plugin, sound effects files cannot be saved to the client

### ISSUE THREAD

**Issue by all85100** [alliedmodders/amxmodx#830]
Regarding the miscstats plug-in, after the server enables the high-speed download function, the sound effect file cannot be saved to the client. Each time the client is reopened, the sound effect file of miscstats is downloaded again

**Comment by OciXCrom** [comment]
I don't think this is a server/AMXX-related issue.

**Comment by xLeviNx** [comment]
There's a template we use here to reproduce the errors OR trying to figure out what the issue at hand is. Nothing you provided is helpful at all @all85100
