### ISSUE TITLE
Reconnect to DB

### ISSUE THREAD

**Issue by Scurraru** [alliedmodders/amxmodx#838]
# Environment
  * Operating System version:  Linux Debian 9
  * Game/AppID (with version if applicable): Half-life HLDS Couter-strike 1.6
  * Current AMX Mod X version:  1.9.0.5263
  * Current Metamod version: Metamod-r v.1.3.0.128
  - [ ] I have updated AMX Mod X to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.
  - [ ] I have updated AMX Mod X to the [latest snapshot](https://www.amxmodx.org/snapshots.php) and it still happens.
  - [ ] I have updated Metamod to the [latest version](https://www.amxmodx.org/downloads.php) and it still happens.

# Description
Reconnecting to the database does not occur

# Problematic Code (or Steps to Reproduce)
#include <amxmodx>
#include <amxmisc>
#include <sqlx>

new Handle:info

public plugin_init()
{
<------>register_plugin("2", "2", "Team")
<------>set_task(5.0, "adminSql",0,"",0,"b")
<------>new configsDir[64]
<------>get_configsdir(configsDir, 63)
<---->SQL_SetAffinity("mysql")
<------>info = SQL_MakeDbTuple("DBIP", "DBUser", "mypass", "DBName")
<------>return PLUGIN_CONTINUE
}

public adminSql()
{
<------>new error[128], errno
<------>new Handle:sql = SQL_Connect(info, errno, error, 127)
...
<------>if(sql == Empty_Handle)
<------>{
<------><------>server_print("[@@@] connect failed info - %d", info)
<------><------>log_amx("[@@@] connect failed info - %d", info)
<------>}
<------>else
<------>{
<------><------>server_print("[@@@] connect OK info - %d", info)
<------><------>log_amx("[@@@] connect OK info - %d", info)
<------><------>SQL_FreeHandle(sql)
<------>}
<------>return PLUGIN_CONTINUE
}

# Logs

L 02/25/2020 - 00:00:05: -------- Mapchange to de_dust --------
L 02/25/2020 - 00:09:58: [GEOIP] Database info: GeoLite2 Country database 2.0
L 02/25/2020 - 00:09:59: -------- Mapchange to de_dust --------
L 02/25/2020 - 00:10:06: [2.amxx] [@@@] connect OK info - 1
L 02/25/2020 - 00:10:11: [2.amxx] [@@@] connect failed info - 1
L 02/25/2020 - 00:10:16: [2.amxx] [@@@] connect failed info - 1
L 02/25/2020 - 00:10:21: [2.amxx] [@@@] connect failed info - 1
L 02/25/2020 - 00:10:26: [2.amxx] [@@@] connect failed info - 1
L 02/25/2020 - 00:10:31: [2.amxx] [@@@] connect failed info - 1
L 02/25/2020 - 00:10:36: [2.amxx] [@@@] connect failed info - 1
L 02/25/2020 - 00:10:41: [2.amxx] [@@@] connect failed info - 1

**Comment by voed** [comment]
Use threaded queries and forget about SQL_Connect forever.

**Comment by afwn90cj93201nixr2e1re** [comment]
printing handler instead error, genius.

**Comment by Scurraru** [comment]
> Use threaded queries and forget about SQL_Connect forever.

Thank`s. It is work.

**Comment by dvander** [comment]
The non-threaded API was a mistake. Do not do I/O, much less networked I/O, on the game thread.
