### ISSUE TITLE
[Feature] Add native (or stock) to search players

### ISSUE THREAD

**Issue by 4D1G06** [alliedmodders/amxmodx#845]
My idea is very simple, can you please implement a function (native or stock) that will find a particular player? For example, if my nickname is "LoneKiller" and I search a player with "lOnE" or "kiLLeR" (**letter case ignored**) it should return my index, else in case of failure return -1 or 0. Thanks.

**Comment by Nextra** [comment]
`get_players` and the flag variant `get_players_ex` should do what you need.

**Comment by 4D1G06** [comment]
> `get_players` and the flag variant `get_players_ex` should do what you need.

That's not quiet the case. This plugin not only is

**Comment by 4D1G06** [comment]
> `get_players` and the flag variant `get_players_ex` should do what you need.

That's not quiet the case. For example amxmisc doesn't exist without a reason, and `get_players` returns an array instead...  Having a unique function would be a bonus.

**Comment by Nextra** [comment]
Then you can use `find_player` or `find_player_ex`.
