### ISSUE TITLE
[compiler] error 001: expected token: ")", but found ";"

### ISSUE THREAD

**Issue by Vaqtincha** [alliedmodders/amxmodx#857]
```
#define CHECK_MAP

     if (MaxClients > 21
#if defined CHECK_MAP 
         && equali(MapName, "de_dust2")
#endif
       )
```
Where is the error in the code?

**Comment by Sushant2** [comment]
this code is in python or which language?
i can help u

**Comment by AdamRichard21st** [comment]
It's probably related to `error 057: unfinished expression before compiler directive`.

Kinda off topic, but, why not just avoiding such problems by going like:
```cpp
    #if defined CHECK_MAP
        if ( MaxClients > 21 && equali( MapName, "de_dust2" ) )
    #else
        if ( MaxClients > 21 )
    #endif
    {
        // something
    }
```

**Comment by Vaqtincha** [comment]
@AdamRichard21st 
I know. but this is not a solution.

**Comment by Vaqtincha** [comment]
This is a compiler issue.

**Comment by AdamRichard21st** [comment]
> @AdamRichard21st
> I know. but this is not a solution.

That's sad it's not enough for *your* use case.
Kinda interesting tho.

**Comment by Vaqtincha** [comment]
@AdamRichard21st 
I just want to find out why.

**Comment by Vaqtincha** [comment]
Waiting for amxcompiler developers.

**Comment by Sushant2** [comment]
okay, fine,
no problem!

**Comment by asherkin** [comment]
The problem here is optional semicolon insertion, I'd say this is behaving as expected.

**Comment by Vaqtincha** [comment]
Even if I comment on #define CHECK_MAP, the error does not disappear.

**Comment by Sushant2** [comment]
write like this, i suppose it works,
```javascript
# defined CHECK_MAP
        # if ( MaxClients > 21 && equali( MapName, "de_dust2" ) )
       {
             //something
         }
  #elif  ( MaxClients > 21 )
        {
             //something
         }
    #endif
    {
        // something
    }
```

**Comment by Vaqtincha** [comment]
Yes, there can be many options. But I want to find out why the compiler considers this a mistake.

**Comment by Sushant2** [comment]
because when compiler tries to compile your code, it gives an error as u have written wrong syntax!

**Comment by Vaqtincha** [comment]
The pawn language is inherited from c ++ and in c ++ my code is correct.

**Comment by Vaqtincha** [comment]
This is a compiler issue.

**Comment by Sushant2** [comment]
ohh okay!
then maybe some other problem is!

**Comment by dvander** [comment]
It's not inherited from C++. You'll find things work better if you don't use preprocessor directives.

**Comment by Vaqtincha** [comment]
pfff
