### ISSUE TITLE
New menu's doesn't support lang keys on More, Next, Exit options

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [alliedmodders/amxmodx#881]

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/alliedmodders/amxmodx/blob/ed1ab00fafc9ae4206848123f28ee590c755e262/amxmodx/newmenus.cpp#L579

https://github.com/alliedmodders/amxmodx/blob/ed1ab00fafc9ae4206848123f28ee590c755e262/amxmodx/newmenus.cpp#L544

https://github.com/alliedmodders/amxmodx/blob/ed1ab00fafc9ae4206848123f28ee590c755e262/amxmodx/newmenus.cpp#L623

**Comment by afwn90cj93201nixr2e1re** [comment]
I can't use...

**Comment by afwn90cj93201nixr2e1re** [comment]
Also then multilang menu's became useless if we can't format them as we wanna (coz now if lang key not found then text not gonna be changed, same with simple items in menu, so, it's not brekable change). Check #882 for more info.

**Comment by Arkshine** [comment]
If you want _deep_ answer, I would suggest first to fix your attitude and making _deep_ explanations in your issues.
Otherwise, any discussion will not be productive because you don't say all. We are not clairvoyant nor we remember everything. Elaborate your thoughts is the best way to get a proper answer. 

It would have been easier and useful to say first that the `ml` param doesn't work on back/next/exit props..

**Comment by afwn90cj93201nixr2e1re** [comment]
Em, wtf dude.
> It would have been easier and useful to say first that the ml param doesn't work on back/next/exit props..

![изображение](https://user-images.githubusercontent.com/9306996/87352751-1e500080-c54b-11ea-9fe1-28f8b2c00e2e.png)


> because you don't say all

possible because im using issue pages? 
![изображение](https://user-images.githubusercontent.com/9306996/87352832-3d4e9280-c54b-11ea-9931-27c023e3ae14.png)

idk how u can miss all of this stuff.

> I would suggest first to fix your attitude and making deep explanations in your issues.

Moslty it's doesnt need at all, coz mostly u just decline them coz u don't wanna make any breakble changes in **NEW** releases, coz then it's can break backward compatibility.
I described it 1 year ago. But as u said:
> We are not clairvoyant nor we remember everything

**Comment by afwn90cj93201nixr2e1re** [comment]
So, if im gonna create PR with fix, r u gonna merge it asap or we again should wait 3-4 months?
