### ISSUE TITLE
CSStatsX only Shots and Deatchs are recorded.

### ISSUE THREAD

**Issue by sourcepowered** [alliedmodders/amxmodx#900]
Using ReHLDS + ReGameDLL + Metamod-R + AMX Mod X 1.9.0-git5271 + Steam CS.
( Everything is the latest version. )

The csstats.dat only recording the Shots and Deaths.

![1](https://user-images.githubusercontent.com/70419030/91703809-5966cb80-ebad-11ea-8dba-09b1e81e0869.png)

**Comment by SmileYzn** [comment]
Did you tested with bots or what? If yes, you can check csstats_rankbots at amxx.cfg

**Comment by sourcepowered** [comment]
@SmileYzn Thank you very much.
