### ISSUE TITLE
Build amxmodx 1.9 .so file size

### ISSUE THREAD

**Issue by xlenonz** [alliedmodders/amxmodx#903]
Hi,

I compile amxmodx 1.9 5271 with success no problem but

my amxmodx_mm_i386.so size is 7.9MB but original amxmodx 1.9 5271 size 1.9MB

my engine_amxx_i386.so size 760KB but original amxmodx 1.9 5171 size 95KB

why that difference how can make it like original?

using fedora 32 64bit for compile.

**Comment by Arkshine** [comment]
How did you compile? It sounds like it's either compiled in debug mode or symbols not stripped. 

Using AMBuild, make sure to pass `--enable-optimize --symbol-files` with `configure.py`.

**Comment by xlenonz** [comment]
okay configure.py --enable-optimize --symbol-files now 2mb.

pls update that page :) https://wiki.alliedmods.net/Building_AMX_Mod_X

**Comment by Arkshine** [comment]
Thanks, it's updated on the wiki now!
