### ISSUE TITLE
[TFCX] Invalid player

### ISSUE THREAD

**Issue by pizzahut2** [alliedmodders/amxmodx#938]
# Environment

  * Operating System version: Linux
  * Game/AppID (with version if applicable): TFC
  * Current AMX Mod X version: v1.10 build 5414
  * Current Metamod version: v1.21p39
  * foxbot "0.793"

# Description

I've updated AMXX from v1.10 build 5406 to build 5414 and got this:

L 03/10/2021 - 01:54:51: [TFCX] Invalid player 1
L 03/10/2021 - 01:54:51: [AMXX] Displaying debug trace (plugin "tf2_player_models.amxx", version "1")
L 03/10/2021 - 01:54:51: [AMXX] Run time error 10: native error (native "tfc_setmodel")
L 03/10/2021 - 01:54:51: [AMXX]    [0] tf2_player_models.sma::player_spawned (line 32)

# Problematic Code (or Steps to Reproduce)

The player models are from this pack, but renamed as seen in plugin_precache:

https://gamebanana.com/skins/125910

```
#include <amxmodx>
#include <engine>
#include <tfcx>

#define PLUGIN "TF2 player models"
#define AUTHOR "pizzahut"
#define VERSION "1"

public plugin_init()
{
  register_plugin(PLUGIN, VERSION, AUTHOR)
  register_event("ResetHUD", "player_spawned", "be")
}

public plugin_precache()
{
  precache_model("models/player/tf2_scout/tf2_scout.mdl")
  precache_model("models/player/tf2_sniper/tf2_sniper.mdl")
  precache_model("models/player/tf2_soldier/tf2_soldier.mdl")
  precache_model("models/player/tf2_demo/tf2_demo.mdl")
  precache_model("models/player/tf2_medic/tf2_medic.mdl")
  precache_model("models/player/tf2_hvyweapon/tf2_hvyweapon.mdl")
  precache_model("models/player/tf2_pyro/tf2_pyro.mdl")
  precache_model("models/player/tf2_spy/tf2_spy.mdl")
  precache_model("models/player/tf2_engineer/tf2_engineer.mdl")
}

public player_spawned(id)
{
  switch(entity_get_int(id, EV_INT_playerclass))
  {
    case TFC_PC_SCOUT: tfc_setmodel(id, "tf2_scout", "")
    case TFC_PC_SNIPER: tfc_setmodel(id, "tf2_sniper", "")
    case TFC_PC_SOLDIER : tfc_setmodel(id, "tf2_soldier", "")
    case TFC_PC_DEMOMAN: tfc_setmodel(id, "tf2_demo", "")
    case TFC_PC_MEDIC: tfc_setmodel(id, "tf2_medic", "")
    case TFC_PC_HWGUY: tfc_setmodel(id, "tf2_hvyweapon", "")
    case TFC_PC_PYRO: tfc_setmodel(id, "tf2_pyro", "")
    case TFC_PC_SPY: tfc_setmodel(id, "tf2_spy", "")
    case TFC_PC_ENGINEER: tfc_setmodel(id, "tf2_engineer", "")
  }
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
I don't understand how is that even possible. Do you use bots on the server?

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok. I see. Definitely. So, basically it's not amxmodx issue. But we will fix it. Whatever.

**Comment by afwn90cj93201nixr2e1re** [comment]
Arkshine, can i add new cvar for strict mode with bots pdata?

**Comment by pizzahut2** [comment]
I assumed it's an AMXX issue because it worked fine with previous versions. I appreciate a work-around if it's down to a bug in FoxBot, though in this case I'll ask the FoxBot maintainer if he has an idea.

**Comment by APGRoboCop** [comment]
Well I'm not too sure but Jeefo from Bots-United helped on FoxBot by removing that performance bugs and to use less CPU last year for FoxBot 0.793

**Comment by asherkin** [comment]
> Ok. I see. Definitely. So, basically it's not amxmodx issue. But we will fix it. Whatever.

Could you please add an explanation of the issue here so that there is a record of it, and so there is some guidance for what changes need to be made.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/alliedmodders/amxmodx/issues/937

The issue is that that kind of plugins working with players that hasn't been connected yet and has no actual valid pdata to work with.

Let me fix it instead explaining too much, because anyway, arkshine did same things with with menu and register message in cstrike...

Answer to your question is - using connection checks, because as we all know spawn (which calls resethud) could be called once before connection.

But as we know people aren't able to fix it for themselves, let us do it, but i need one extra cvar to keep people from making these mistakes again and again.

**Comment by afwn90cj93201nixr2e1re** [comment]
I'll make new pr in a hour. Don't worry.

**Comment by asherkin** [comment]
> because as we all know spawn could be called once before connection.

I don't think that is at all obvious.

FWIW, SourceMod does a bunch of work with bots to make sure plugins see things happen in the same order as if they were regular players - I think the same would make sense here. Plugins shouldn't have to care about handling bots explicitly if they don't want to.

**Comment by afwn90cj93201nixr2e1re** [comment]
I agree with you.
The problem is that someone in the 2000s implemented it in a such incorrect way.
This is amxmodx's design problem, not GameDLL.
I ran into it while i was testing my first fix (which wastn ready when David merged it), so i had to immediately  implement the additional one.

In fact, with these fixes we also solving the problem of phantom invalid pdatas, which showed itself best in the menu with cstrike mod.
https://github.com/alliedmodders/amxmodx/pull/863

It turned out like this: after map change the first connected player was the bot and since the bot doesn't have a pdata during the first connection attempt (this is the first player and bot's doesnt receive actual pdata before *bot 1 appears in userinfo (https://github.com/alliedmodders/amxmodx/pull/917/files#diff-54b869dfe0d395e12ab5b3107d2ab77fc575c4f68d8dd9c678c8d65985929015R1022)) plugins at the same time tried to install values to an invalid address nullptr most likely which were covered by `->ingame` checks ( and servers were crashing.
Same thing is in this topic and in near one.

**Comment by pizzahut2** [comment]
Indeed I thought a player is connected when the HUD gets reset. I realise he could still be spectating due to the "register_event" bug with the "alive" flag. It worked fine though before updating, and after reverting to 1.9, it immediately worked again (and no further errors in the AMXX logs).

The problem was that the bots didn't change model at all, not when actually spawning or when respawning after death. Not sure why.

**Comment by afwn90cj93201nixr2e1re** [comment]
Not always. The first one could be false positive, in cs it is. Probably it was copy pasted into other gamedlls as well.
It 'worked'. The main issues that you haven't noticed about that yet.

Can you try to make it like this:

```pawn
#include <amxmodx>
#include <engine>
#include <tfcx>

#define PLUGIN "TF2 player models"
#define AUTHOR "pizzahut"
#define VERSION "1"

public plugin_init()
{
  register_plugin(PLUGIN, VERSION, AUTHOR)
  register_event("ResetHUD", "player_spawned", "be")
}

public plugin_precache()
{
  precache_model("models/player/tf2_scout/tf2_scout.mdl");
  precache_model("models/player/tf2_sniper/tf2_sniper.mdl");
  precache_model("models/player/tf2_soldier/tf2_soldier.mdl");
  precache_model("models/player/tf2_demo/tf2_demo.mdl");
  precache_model("models/player/tf2_medic/tf2_medic.mdl");
  precache_model("models/player/tf2_hvyweapon/tf2_hvyweapon.mdl");
  precache_model("models/player/tf2_pyro/tf2_pyro.mdl");
  precache_model("models/player/tf2_spy/tf2_spy.mdl");
  precache_model("models/player/tf2_engineer/tf2_engineer.mdl");
}

public player_spawned(id)
{
  if(!is_user_alive(id)) return;
  switch(entity_get_int(id, EV_INT_playerclass))
  {
    case TFC_PC_SCOUT: tfc_setmodel(id, "tf2_scout", "");
    case TFC_PC_SNIPER: tfc_setmodel(id, "tf2_sniper", "");
    case TFC_PC_SOLDIER : tfc_setmodel(id, "tf2_soldier", "");
    case TFC_PC_DEMOMAN: tfc_setmodel(id, "tf2_demo", "");
    case TFC_PC_MEDIC: tfc_setmodel(id, "tf2_medic", "");
    case TFC_PC_HWGUY: tfc_setmodel(id, "tf2_hvyweapon", "");
    case TFC_PC_PYRO: tfc_setmodel(id, "tf2_pyro", "");
    case TFC_PC_SPY: tfc_setmodel(id, "tf2_spy", "");
    case TFC_PC_ENGINEER: tfc_setmodel(id, "tf2_engineer", "");
  }
}
```

and yes, as you said probably flag "e" doesn't extra `->ingame` checks.

**Comment by pizzahut2** [comment]
It's always failing the is_user_alive test for some reason. I have added some debugging code.

I did compile with AMXX 1.9, is this ok? I wanted the ".amxx" to be compatible with both 1.9 and 1.10.

Creating bot...
ResetHUD/be for player 1 - not actually alive
ResetHUD/b for player 1
ResetHUD/b for player 1

Creating bot...
ResetHUD/be for player 2 - not actually alive
ResetHUD/b for player 2

ResetHUD/be for player 1 - not actually alive
ResetHUD/b for player 1

ResetHUD/b for player 2
ResetHUD/be for player 2 - not actually alive
ResetHUD/b for player 2

```
#include <amxmodx>
#include <engine>
#include <tfcx>

#define PLUGIN "TF2 player models"
#define AUTHOR "pizzahut"
#define VERSION "1.1"

public plugin_init()
{
  register_plugin(PLUGIN, VERSION, AUTHOR)
  register_event("ResetHUD", "player_spawned", "be")
  register_event("ResetHUD", "player_spawn_test", "b")
}

public plugin_precache()
{
  precache_model("models/player/tf2_scout/tf2_scout.mdl")
  precache_model("models/player/tf2_sniper/tf2_sniper.mdl")
  precache_model("models/player/tf2_soldier/tf2_soldier.mdl")
  precache_model("models/player/tf2_demo/tf2_demo.mdl")
  precache_model("models/player/tf2_medic/tf2_medic.mdl")
  precache_model("models/player/tf2_hvyweapon/tf2_hvyweapon.mdl")
  precache_model("models/player/tf2_pyro/tf2_pyro.mdl")
  precache_model("models/player/tf2_spy/tf2_spy.mdl")
  precache_model("models/player/tf2_engineer/tf2_engineer.mdl")
}

public player_spawned(id)
{
  if (!is_user_alive(id))
  {
    server_print("ResetHUD/be for player %d - not actually alive",id)
    return
  }
  server_print("ResetHUD/be for player %d - is really alive",id)

  switch(entity_get_int(id, EV_INT_playerclass))
  {
    case TFC_PC_SCOUT: tfc_setmodel(id, "tf2_scout", "")
    case TFC_PC_SNIPER: tfc_setmodel(id, "tf2_sniper", "")
    case TFC_PC_SOLDIER : tfc_setmodel(id, "tf2_soldier", "")
    case TFC_PC_DEMOMAN: tfc_setmodel(id, "tf2_demo", "")
    case TFC_PC_MEDIC: tfc_setmodel(id, "tf2_medic", "")
    case TFC_PC_HWGUY: tfc_setmodel(id, "tf2_hvyweapon", "")
    case TFC_PC_PYRO: tfc_setmodel(id, "tf2_pyro", "")
    case TFC_PC_SPY: tfc_setmodel(id, "tf2_spy", "")
    case TFC_PC_ENGINEER: tfc_setmodel(id, "tf2_engineer", "")
  }
}

public player_spawn_test(id)
{
  server_print("ResetHUD/b for player %d",id)
}
```

**Comment by pizzahut2** [comment]
This is with 1.9:

Creating bot...
ResetHUD/be for player 1 - not actually alive
ResetHUD/b for player 1
ResetHUD/b for player 1
Creating bot...
ResetHUD/be for player 1 - is really alive
ResetHUD/b for player 1
ResetHUD/be for player 2 - not actually alive
ResetHUD/b for player 2
ResetHUD/b for player 2
Creating bot...
ResetHUD/be for player 2 - is really alive
ResetHUD/b for player 2

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you add client_putinserver log?
```
public client_putinserver(id) log_amx("Client %d connected", id);
public client_connect(id) log_amx("Client %d is connecting", id);
public client_disconnected(id) log_amx("Client %d disconnected", id);
```

**Comment by pizzahut2** [comment]
bot addbot
Client 1 is connecting
Creating bot...
Client 1 is connecting
ResetHUD/b for player 1 - connected, dead
ResetHUD/b for player 1 - connected, dead
Client 1 is connecting
ResetHUD/b for player 1 - connected, dead
Client 1 is connecting
```
#include <amxmodx>
#include <engine>
#include <tfcx>

#define PLUGIN "TF2 player models"
#define AUTHOR "pizzahut"
#define VERSION "1.2"

public plugin_init()
{
  register_plugin(PLUGIN, VERSION, AUTHOR)
  register_event("ResetHUD", "event_ResetHUD", "b")
}

public client_putinserver(id) server_print("Client %d connected", id)
public client_connect(id) server_print("Client %d is connecting", id)
public client_disconnected(id) server_print("Client %d disconnected", id)

public event_ResetHUD(id)
{
  if (!is_user_alive(id))
  {
    if (is_user_connected(id))
      server_print("ResetHUD/b for player %d - connected, dead",id)
    else
      server_print("ResetHUD/b for player %d - not connected",id)
    return
  }
  server_print("ResetHUD/b for player %d - connected, alive",id)

  switch(entity_get_int(id, EV_INT_playerclass))
  {
    case TFC_PC_SCOUT: tfc_setmodel(id, "tf2_scout", "")
    case TFC_PC_SNIPER: tfc_setmodel(id, "tf2_sniper", "")
    case TFC_PC_SOLDIER : tfc_setmodel(id, "tf2_soldier", "")
    case TFC_PC_DEMOMAN: tfc_setmodel(id, "tf2_demo", "")
    case TFC_PC_MEDIC: tfc_setmodel(id, "tf2_medic", "")
    case TFC_PC_HWGUY: tfc_setmodel(id, "tf2_hvyweapon", "")
    case TFC_PC_PYRO: tfc_setmodel(id, "tf2_pyro", "")
    case TFC_PC_SPY: tfc_setmodel(id, "tf2_spy", "")
    case TFC_PC_ENGINEER: tfc_setmodel(id, "tf2_engineer", "")
  }
}

public plugin_precache()
{
  precache_model("models/player/tf2_scout/tf2_scout.mdl")
  precache_model("models/player/tf2_sniper/tf2_sniper.mdl")
  precache_model("models/player/tf2_soldier/tf2_soldier.mdl")
  precache_model("models/player/tf2_demo/tf2_demo.mdl")
  precache_model("models/player/tf2_medic/tf2_medic.mdl")
  precache_model("models/player/tf2_hvyweapon/tf2_hvyweapon.mdl")
  precache_model("models/player/tf2_pyro/tf2_pyro.mdl")
  precache_model("models/player/tf2_spy/tf2_spy.mdl")
  precache_model("models/player/tf2_engineer/tf2_engineer.mdl")
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok, lets fix bots.

**Comment by pizzahut2** [comment]
Just for comparison, human player:

Client 1 is connecting
Client 1 connected
ResetHUD/b for player 1 - connected, dead
ResetHUD/b for player 1 - connected, alive
Client 1 disconnected
Dropped pizzahut.SoK from server
Reason:  Client sent 'drop'

**Comment by afwn90cj93201nixr2e1re** [comment]
Yes, i know, you should use is_user_connected_ex for strict results.

![изображение](https://user-images.githubusercontent.com/9306996/110943514-32930a00-8333-11eb-86e5-2ded364c3231.png)


[foxbot.zip](https://github.com/alliedmodders/amxmodx/files/6130218/foxbot.zip)

Try this version.

**Comment by afwn90cj93201nixr2e1re** [comment]
Update amxmodx to the latest version

**Comment by pizzahut2** [comment]
Updated FoxBot works with "old" build 5414. (Client 1 is alive after 2s.)

Client 1 is connecting (connect)
Creating bot...
Client 1 connected (putinserver)
Client 1 ResetHUD alive:no connected:yes connected_ex:yes
L 03/12/2021 - 20:06:12: "Lance<1><BOT><>" entered the game
L 03/12/2021 - 20:06:12: "Lance<1><BOT><>" joined team "SPECTATOR"
L 03/12/2021 - 20:06:12: "Lance<1><BOT><>" joined team "SPECTATOR"
Client 1 ResetHUD alive:no connected:yes connected_ex:yes
Client 2 is connecting (connect)
Creating bot...
Client 2 connected (putinserver)
Client 2 ResetHUD alive:no connected:yes connected_ex:yes
L 03/12/2021 - 20:06:13: "Harvey<2><BOT><>" entered the game
L 03/12/2021 - 20:06:13: "Harvey<2><BOT><>" joined team "SPECTATOR"
L 03/12/2021 - 20:06:13: "Harvey<2><BOT><>" joined team "SPECTATOR"
Client 2 ResetHUD alive:no connected:yes connected_ex:yes
L 03/12/2021 - 20:06:13: "Lance<1><BOT><SPECTATOR>" joined team "Blue"
Client 3 is connecting (connect)
Creating bot...
Client 3 connected (putinserver)
L 03/12/2021 - 20:06:14: "Lance<1><BOT><Blue>" changed role to "Medic"
L 03/12/2021 - 20:06:14: "Lance<1><BOT><Blue>" triggered "info_player_teamspawn"
Client 1 ResetHUD alive:yes connected:yes connected_ex:yes
Client 3 ResetHUD alive:no connected:yes connected_ex:yes
L 03/12/2021 - 20:06:14: "Charlie<3><BOT><>" entered the game
L 03/12/2021 - 20:06:14: "Charlie<3><BOT><>" joined team "SPECTATOR"
L 03/12/2021 - 20:06:14: "Harvey<2><BOT><SPECTATOR>" joined team "Red"
L 03/12/2021 - 20:06:14: "Charlie<3><BOT><>" joined team "SPECTATOR"
Client 3 ResetHUD alive:no connected:yes connected_ex:yes
L 03/12/2021 - 20:06:15: "Harvey<2><BOT><Red>" changed role to "HWGuy"
L 03/12/2021 - 20:06:15: "Harvey<2><BOT><Red>" triggered "info_player_teamspawn"
Client 2 ResetHUD alive:yes connected:yes connected_ex:yes

```
#include <amxmodx>
#include <engine>
#include <tfcx>

public plugin_init()
{
  register_plugin("TF2 player models", "1.3", "pizzahut")
  register_event("ResetHUD", "event_ResetHUD", "b")
}

public client_connect(id) server_print("Client %d is connecting (connect)", id)
#if AMXX_VERSION_NUM >= 190
public client_connectex(id, const name[], const ip[], reason[128])
{
  server_print("Client %d is connecting (connectex)", id)
  return PLUGIN_CONTINUE
}
#endif
public client_putinserver(id) server_print("Client %d connected (putinserver)", id)
public client_disconnected(id) server_print("Client %d disconnected", id)

public event_ResetHUD(id)
{
  #if AMXX_VERSION_NUM >= 200
  server_print("Client %d ResetHUD alive:%s connected:%s connected_ex:%s", id,
    is_user_alive(id)?"yes":"no",
    is_user_connected(id)?"yes":"no",
    is_user_connected_ex(id)?"yes":"no")
  #else
  server_print("Client %d ResetHUD alive:%s connected:%s", id,
    is_user_alive(id)?"yes":"no",
    is_user_connected(id)?"yes":"no",
  #endif
  if (!is_user_alive(id))
    return
  switch(entity_get_int(id, EV_INT_playerclass))
  {
    case TFC_PC_SCOUT: tfc_setmodel(id, "tf2_scout", "")
    case TFC_PC_SNIPER: tfc_setmodel(id, "tf2_sniper", "")
    case TFC_PC_SOLDIER : tfc_setmodel(id, "tf2_soldier", "")
    case TFC_PC_DEMOMAN: tfc_setmodel(id, "tf2_demo", "")
    case TFC_PC_MEDIC: tfc_setmodel(id, "tf2_medic", "")
    case TFC_PC_HWGUY: tfc_setmodel(id, "tf2_hvyweapon", "")
    case TFC_PC_PYRO: tfc_setmodel(id, "tf2_pyro", "")
    case TFC_PC_SPY: tfc_setmodel(id, "tf2_spy", "")
    case TFC_PC_ENGINEER: tfc_setmodel(id, "tf2_engineer", "")
  }
}

public plugin_precache()
{
  precache_model("models/player/tf2_scout/tf2_scout.mdl")
  precache_model("models/player/tf2_sniper/tf2_sniper.mdl")
  precache_model("models/player/tf2_soldier/tf2_soldier.mdl")
  precache_model("models/player/tf2_demo/tf2_demo.mdl")
  precache_model("models/player/tf2_medic/tf2_medic.mdl")
  precache_model("models/player/tf2_hvyweapon/tf2_hvyweapon.mdl")
  precache_model("models/player/tf2_pyro/tf2_pyro.mdl")
  precache_model("models/player/tf2_spy/tf2_spy.mdl")
  precache_model("models/player/tf2_engineer/tf2_engineer.mdl")
}
```

**Comment by pizzahut2** [comment]
Bad load with 5416 since the is_user_connect_ex function is gone.

 [ 36] 35  unknown                 unknown     unknown           unknown                          tf2_player_  bad load
( 36) Load fails: Plugin uses an unknown function (name "is_user_connected_ex") - check your modules.ini.

**Comment by pizzahut2** [comment]
Works fine after removing this function with fixed FoxBot, AMXX build 5416:

Bot per team balance Off

--All bot commands must be enclosed in quotes--
e.g. bot "bot_chat 20"

Client 1 is connecting (connect)
Client 1 connected (putinserver)
Creating bot...
Client 1 ResetHUD alive:no connected:yes
L 03/12/2021 - 20:42:54: "Alvin Steele<11><BOT><>" entered the game
L 03/12/2021 - 20:42:54: "Alvin Steele<11><BOT><>" joined team "SPECTATOR"
L 03/12/2021 - 20:42:55: "Alvin Steele<11><BOT><>" joined team "SPECTATOR"
Client 1 ResetHUD alive:no connected:yes
Client 2 is connecting (connect)
Client 2 connected (putinserver)
Creating bot...
Client 2 ResetHUD alive:no connected:yes
L 03/12/2021 - 20:42:55: "Peter<12><BOT><>" entered the game
L 03/12/2021 - 20:42:55: "Peter<12><BOT><>" joined team "SPECTATOR"
2fort.cfg
L 03/12/2021 - 20:42:56: "Alvin Steele<11><BOT><SPECTATOR>" joined team "Blue"
L 03/12/2021 - 20:42:56: "Peter<12><BOT><>" joined team "SPECTATOR"
Client 2 ResetHUD alive:no connected:yes
Client 3 is connecting (connect)
Client 3 connected (putinserver)
Creating bot...
L 03/12/2021 - 20:42:56: "Alvin Steele<11><BOT><Blue>" changed role to "Scout"
L 03/12/2021 - 20:42:56: "Alvin Steele<11><BOT><Blue>" triggered "info_player_teamspawn"
Client 1 ResetHUD alive:yes connected:yes
Client 3 ResetHUD alive:no connected:yes
L 03/12/2021 - 20:42:56: "Customer<13><BOT><>" entered the game
L 03/12/2021 - 20:42:56: "Customer<13><BOT><>" joined team "SPECTATOR"
L 03/12/2021 - 20:42:57: "Peter<12><BOT><SPECTATOR>" joined team "Red"
L 03/12/2021 - 20:42:57: "Customer<13><BOT><>" joined team "SPECTATOR"
Client 3 ResetHUD alive:no connected:yes
Client 4 is connecting (connect)
Client 4 connected (putinserver)
Creating bot...
L 03/12/2021 - 20:42:57: "Peter<12><BOT><Red>" changed role to "Spy"
L 03/12/2021 - 20:42:57: "Peter<12><BOT><Red>" triggered "info_player_teamspawn"
Client 2 ResetHUD alive:yes connected:yes
Client 4 ResetHUD alive:no connected:yes
L 03/12/2021 - 20:42:57: "Judee<14><BOT><>" entered the game
L 03/12/2021 - 20:42:57: "Judee<14><BOT><>" joined team "SPECTATOR"
L 03/12/2021 - 20:42:58: "Customer<13><BOT><SPECTATOR>" joined team "Blue"
L 03/12/2021 - 20:42:58: "Judee<14><BOT><>" joined team "SPECTAT

**Comment by pizzahut2** [comment]
Did a quick test with the original version 1 of my plugin (which doesn't check alive state) and the unpatched FoxBot 0.793, and it seems to work fine with AMXX build 5416.
