### ISSUE TITLE
Add set_hudmessage2

### ISSUE THREAD

**Issue by RauliTop** [alliedmodders/amxmodx#980]
I need to change rgb white color when hud flicks, it is hard-coded here (255, 255, 250): https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/util.cpp#L225

And here: https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/amxmodx.cpp#L547 

So, it's necessary to add a new native to achieve that or add new params after channel at set_hudmessage.

Something like this: https://forums.alliedmods.net/showthread.php?t=69263

But I need SyncHud. That's why I can't use that stock

**Comment by francoromaniello** [comment]
Done in #981
