### ISSUE TITLE
[Build] checkout-deps.sh pip - python version mismatch

### ISSUE THREAD

**Issue by ShootingKing-AM** [alliedmodders/amxmodx#995]
# Issue
Recent builds are failing on [Travis-CI](https://travis-ci.org/github/alliedmodders/amxmodx/builds/768378506) and the build fails locally when no <kbd>pip</kbd> is installed on python version *less than* <kbd>Python3.6</kbd>

# Why
Relavant logs from Travis (same are found locally)

```bash
The detected Python installation does not have PIP

Installing the latest version of PIP available (VIA "get-pip.py")
--2021-04-26 06:36:11--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1936711 (1.8M) [text/x-python]
Saving to: ‘./get-pip.py’

./get-pip.py        100%[===================>]   1.85M  --.-KB/s    in 0.08s   
2021-04-26 06:36:12 (23.3 MB/s) - ‘./get-pip.py’ saved [1936711/1936711]

ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.
Installation of PIP has failed

The command "$CHECKOUT_DIR/support/checkout-deps.sh && cd $CHECKOUT_DIR" failed and exited with 1 during .

Your build has been stopped.
```

Issue is because of, https://github.com/alliedmodders/amxmodx/blob/8fefd48af24f18b74948769ec66669b3a6c5f5ec/support/checkout-deps.sh#L95-L131

Relevant code from, https://bootstrap.pypa.io/get-pip.py, will only work for python min version 3.6.
```python
this_python = sys.version_info[:2]
min_version = (3, 6)
if this_python < min_version:
    message_parts = [
        "This script does not work on Python {}.{}".format(*this_python),
        "The minimum supported Python version is {}.{}.".format(*min_version),
        "Please use https://bootstrap.pypa.io/pip/{}.{}/get-pip.py instead.".format(*this_python),
    ]
    print("ERROR: " + " ".join(message_parts))
    sys.exit(1)
```

# Solutions
1. (Recommended) We can drop support for Python2([End of Life](https://www.python.org/doc/sunset-python-2/)) and keep Python3.6 as min requirement for building Amxmodx.
    > Sunsetting Python 2
    We are volunteers who make and take care of the Python programming language. We have decided that January 1, 2020, was the day that we sunset Python 2. That means that we will not improve it anymore after that day, even if someone finds a security problem in it. You should upgrade to Python 3 as soon as you can.

2. (Not recommended) We can use older version of <kbd>get-pip.py</kbd> from https://bootstrap.pypa.io/pip/2.7/get-pip.py

What do you guys think ?

**Comment by dvander** [comment]
I agree that dropping support for Python 2.7 is the way to go here. I think I addressed this on buildbot already, so it should be NBD to follow suit with GitHub CI or Travis.
