### ISSUE TITLE
[Wiki] Wiki is not being maintained

### ISSUE THREAD

**Issue by ShootingKing-AM** [alliedmodders/amxmodx#996]
There is valuable info in wiki.alliedmods.net/Amxmodx, but its not being updated since the core team is busy with someother things. Why not move to github-wiki/github-pages ?

Github-Pages have the following benefits,
- More contributor partcipation, since Github is now the standard open-source landscape + contributions get profiled here
- Much more transparent than MediaWiki
- Much more easier to implement and track changes
- Much more user-friendly traversing between different pages
- Updates into Wiki are not notifed to users/devs compared to much more reach in github
- Contributions into wiki also have lesser public participation since of reach

Furthur Github-Pages have some [limitations](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits), which most probably wont be hit.
> GitHub Pages sites are subject to the following usage limits:
> - GitHub Pages source repositories have a recommended limit of 1GB. For more information, see "What is my disk quota?"
> - Published GitHub Pages sites may be no larger than 1 GB.
> - GitHub Pages sites have a soft bandwidth limit of 100GB per month.
> - GitHub Pages sites have a soft limit of 10 builds per hour.

**Comment by dvander** [comment]
Anyone can maintain the wiki. It's a wiki. Just log in with a forum account and start editing. The reason no one maintains it is not because it's not on GitHub. It's because writing documentation is not fun for most people.

**Comment by ShootingKing-AM** [comment]
Sorry, but i feel that its unfair to say people do not wish to write/update documentation :( 
Infact, Many of the PRs here are related to Documentation in .inc(s). Even, `Code/Snippnets/Tutorials Section` of Amxmodx Forums is also active till date. 
Github forces Repo Owners/Maintainers to give credit to contributors even if the software inheriently dosent. Also the reason why, the Wiki is only updated by 2-3 official team members and code base on github has 50 odd non-official contributors.

I think, if amxmodx is to be sustainable, we have to make it easier for people to contribute.

**Comment by dvander** [comment]
I'm not sure what that means. It's very easy to contribute. Log in with a forum account and start editing.

**Comment by dvander** [comment]
One other thought - I'm not opposed to GH wiki, since it's just a repo of markdown docs, and changes would need review (currently our wiki has no review policy). I think for new projects the markdown approach is great.

But... who is going to do the work of porting all the AMXX docs over, including any translations and attached media? It's a huge task even if automated tools exist. If someone is offering to do that task we can chat.

**Comment by ShootingKing-AM** [comment]
> But... who is going to do the work of porting all the AMXX docs over, including any translations and attached media? It's a huge task even if automated tools exist. If someone is offering to do that task we can chat.

There are tools to convert mediaWiki to markdown Eg. [This ](https://github.com/philipashlock/mediawiki-to-markdown)and [This](https://github.com/outofcontrol/mediawiki-to-gfm). We can atleast try.

**Comment by dvander** [comment]
Sure, you're welcome to give it a try. It looks like anyone can do it.
